import { SPACE_SCALE, TEXT_SCALE, cssVar } from './tokens.js';
import type { FigmaImportIR } from './types.js';

function customColorBlock(ir: FigmaImportIR): string {
  const customs = ir.colors.filter((color) => !color.token);
  if (customs.length === 0) return '';
  const lines = customs.map((color, index) => {
    const hex = color.opacity < 1
      ? `color-mix(in srgb, ${color.hex} ${Math.round(color.opacity * 100)}%, transparent)`
      : color.hex;
    return `  --figma-c${index + 1}: ${hex};`;
  });
  return `\n:root {\n  /* Colors from the file that did not snap to a brand token */\n${lines.join('\n')}\n}\n`;
}

export function generateUtilityCss(ir: FigmaImportIR): string {
  const gapRules = SPACE_SCALE.map(
    (step) => `.figma-gap-${step.token.replace('space-', '')} { gap: ${cssVar(step.token, `${step.px}px`)}; }`,
  );
  const padRules = SPACE_SCALE.map(
    (step) => `.figma-pad-${step.token.replace('space-', '')} { padding: ${cssVar(step.token, `${step.px}px`)}; }`,
  );
  const textRules = TEXT_SCALE.map(
    (step) => `.figma-text-${step.token.replace('text-', '')} { font-size: ${cssVar(step.token, `${step.px}px`)}; }`,
  );

  return `/* Generated by Code Buddy Figma import.
 * Utility classes bind to the design-system token spine
 * (--bg, --fg, --space-*, --text-*, --radius-md, --font-body).
 * Import this AFTER design-system.css so the brand wins the cascade.
 */

.figma-screen {
  position: relative;
  box-sizing: border-box;
  min-height: 100%;
  background: ${cssVar('bg', '#ffffff')};
  color: ${cssVar('fg', '#111111')};
  font-family: ${cssVar('font-body', 'system-ui, sans-serif')};
}

.figma-frame,
.figma-rect,
.figma-image,
.figma-text {
  box-sizing: border-box;
}

.figma-frame {
  display: flex;
}

.figma-frame-col { flex-direction: column; }
.figma-frame-row { flex-direction: row; align-items: stretch; }
.figma-frame-grid { display: grid; }
.figma-frame-abs { display: block; position: relative; }

.figma-text {
  margin: 0;
  font-family: ${cssVar('font-body', 'system-ui, sans-serif')};
  color: ${cssVar('fg', '#111111')};
  line-height: ${cssVar('leading-body', '1.4')};
}

.figma-rect {
  background: ${cssVar('surface', '#ffffff')};
}

.figma-image {
  background-color: ${cssVar('surface', '#f4f4f4')};
  background-size: cover;
  background-position: center;
}

.figma-fill-bg { background: ${cssVar('bg', '#ffffff')}; }
.figma-fill-surface { background: ${cssVar('surface', '#ffffff')}; }
.figma-fill-fg { background: ${cssVar('fg', '#000000')}; }
.figma-fill-accent { background: ${cssVar('accent', '#000000')}; }
.figma-fill-muted { background: ${cssVar('muted', '#8c8c8c')}; }
.figma-fill-success { background: ${cssVar('success', '#16a34a')}; }
.figma-fill-warn { background: ${cssVar('warn', '#eab308')}; }
.figma-fill-danger { background: ${cssVar('danger', '#dc2626')}; }

.figma-color-fg { color: ${cssVar('fg', '#000000')}; }
.figma-color-muted { color: ${cssVar('muted', '#8c8c8c')}; }
.figma-color-accent { color: ${cssVar('accent', '#000000')}; }

.figma-radius-md { border-radius: ${cssVar('radius-md', '8px')}; }
.figma-radius-sm { border-radius: ${cssVar('radius-sm', '50px')}; }
.figma-radius-pill { border-radius: ${cssVar('radius-pill', '9999px')}; }

${gapRules.join('\n')}
${padRules.join('\n')}
${textRules.join('\n')}
${customColorBlock(ir)}`;
}
