/**
 * Bridges the Cowork media surface to the CORE image_generate tool (loaded from
 * the embedded engine via loadCoreModule), so the GUI can generate images with
 * whatever backend the core is configured for (local ComfyUI / cloud). The core
 * module loader is injected so this is unit-testable without the engine.
 */
import { homedir } from 'os';
import { constants as fsConstants } from 'fs';
import { lstat, open, realpath, writeFile } from 'fs/promises';
import { extname, isAbsolute, join, relative, resolve, sep } from 'path';
import { loadCoreModule } from '../utils/core-loader.js';
import {
  ImageEditHistoryStore,
  type ImageEditHistory,
} from './image-edit-history-store.js';
import { assessEditorialQuality } from '../../shared/editorial-quality.js';
import type { CreativeAsset } from '../../shared/creative-assets.js';

export interface MediaGenRequest {
  prompt: string;
  aspect?: string;
  /** Override CODEBUDDY_IMAGE_PROVIDER for this call (comfyui|openai|xai). */
  provider?: string;
  /** Override CODEBUDDY_IMAGE_MODEL for this call. */
  model?: string;
}

export interface MediaGenResponse {
  ok: boolean;
  outputPath?: string;
  url?: string;
  metadataPath?: string;
  history?: ImageEditHistory;
  error?: string;
}

export interface EditorialMetadataRequest {
  title: string;
  description: string;
  series?: string;
  syntheticMediaDisclosure: boolean;
  prompt: string;
  assetIds: string[];
  previousPrompts?: string[];
}

export interface AssembleVideoRequest {
  clips?: string[];
  aspect?: string;
  name?: string;
  editorial?: EditorialMetadataRequest;
}

export interface ImageEditHistoryResponse {
  ok: boolean;
  history?: ImageEditHistory;
  error?: string;
}

export interface ImageEditRequest {
  prompt: string;
  imagePath?: string;
  imageAssetId?: string;
  /** PNG data URL generated by the renderer canvas; never persisted directly. */
  maskDataUrl?: string;
  selections?: Array<{ x: number; y: number; width: number; height: number }>;
  provider?: string;
  model?: string;
}

export interface MediaGenCapabilities {
  imageGeneration: boolean;
  imageReferences: boolean;
  imageEditing: boolean;
  imageMasking: boolean;
  videoGeneration: boolean;
  videoReferences: boolean;
  firstFrame: boolean;
  lastFrame: boolean;
  audio: boolean;
  provider: string;
  model: string;
}

export interface VideoGenRequest extends MediaGenRequest {
  duration?: number;
  audio?: boolean;
  imagePath?: string;
  referenceImagePaths?: string[];
  imageAssetId?: string;
  referenceAssetIds?: string[];
}

interface CoreMediaModule {
  generateImage(
    input: { prompt: string; aspectRatio?: string },
    runtime?: { env?: NodeJS.ProcessEnv; rootDir?: string },
  ): Promise<{ outputPath?: string; image: string | null }>;
  editImage?(
    input: {
      prompt: string;
      imageUrl: string;
      sourceRef?: string;
      maskUrl?: string;
      selections?: Array<{ x: number; y: number; width: number; height: number }>;
    },
    runtime?: { env?: NodeJS.ProcessEnv; rootDir?: string },
  ): Promise<{ outputPath?: string; image: string | null }>;
  getImageEditCapabilities?(
    runtime?: { env?: NodeJS.ProcessEnv; rootDir?: string },
  ): Promise<{ provider: string; available: boolean; alphaMasking: boolean; reason?: string }>;
  generateVideo?(
    input: {
      prompt: string;
      imageUrl?: string;
      referenceImageUrls?: string[];
      duration?: number;
      aspectRatio?: string;
      resolution?: string;
      audio?: boolean;
      model?: string;
    },
    runtime?: { env?: NodeJS.ProcessEnv; rootDir?: string },
  ): Promise<{ outputPath?: string; video: string | null }>;
}

interface CoreFilmAssemblerModule {
  assembleFilm(input: {
    clips: string[];
    transitions?: string;
    transitionDuration?: number;
    resolution?: string;
    aspectRatio?: string;
    rootDir?: string;
    name?: string;
  }): Promise<{ success: boolean; outputPath?: string; estimatedDuration?: number; warnings?: string[]; error?: string }>;
}

type CoreLoader = () => Promise<CoreMediaModule | null>;
type AssemblerLoader = () => Promise<CoreFilmAssemblerModule | null>;
type MediaWorkspaceRootsLoader = () => Iterable<string>;
type MediaRootLoader = string | (() => string);
type AssetPathResolver = (id: string) => Promise<string>;
type AssetMetadataResolver = (id: string) => Promise<CreativeAsset>;

/** Map the GUI aspect (1:1 / 16:9 / 9:16) to the core's aspect ratio names. */
export function aspectToRatio(aspect?: string): 'landscape' | 'square' | 'portrait' {
  if (aspect === '16:9') return 'landscape';
  if (aspect === '9:16') return 'portrait';
  return 'square';
}

export class MediaGenService {
  private modPromise?: Promise<CoreMediaModule | null>;
  private assemblerPromise?: Promise<CoreFilmAssemblerModule | null>;
  private readonly mediaWorkspaceRootsLoader: MediaWorkspaceRootsLoader;
  private readonly imageEditHistoryStores = new Map<string, ImageEditHistoryStore>();

  constructor(
    private readonly loader: CoreLoader = () => loadCoreModule<CoreMediaModule>('tools/media-generation-tool.js'),
    private readonly rootDir: MediaRootLoader = homedir(),
    private readonly assemblerLoader: AssemblerLoader = () => loadCoreModule<CoreFilmAssemblerModule>('tools/video/film-assemble.js'),
    mediaWorkspaceRootsLoader?: MediaWorkspaceRootsLoader,
    private readonly assetPathResolver?: AssetPathResolver,
    private readonly assetMetadataResolver?: AssetMetadataResolver,
  ) {
    this.mediaWorkspaceRootsLoader = mediaWorkspaceRootsLoader ?? (() => []);
  }

  async generateImage(req: MediaGenRequest): Promise<MediaGenResponse> {
    const prompt = (req?.prompt ?? '').trim();
    if (!prompt) return { ok: false, error: 'prompt is required' };
    const rootDir = this.currentRootDir();

    const mod = await (this.modPromise ??= this.loader());
    if (!mod?.generateImage) {
      return { ok: false, error: 'core media module unavailable (is the embedded engine configured?)' };
    }

    const env: NodeJS.ProcessEnv = { ...process.env };
    if (req.provider) env.CODEBUDDY_IMAGE_PROVIDER = req.provider;
    if (req.model) env.CODEBUDDY_IMAGE_MODEL = req.model;

    try {
      const res = await mod.generateImage(
        { prompt, aspectRatio: aspectToRatio(req.aspect) },
        { env, rootDir },
      );
      const outputPath = res.outputPath ?? res.image ?? undefined;
      if (!outputPath) return { ok: false, error: 'image generation returned no local path' };
      return { ok: true, outputPath, url: `file://${outputPath}` };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }

  async editImage(req: ImageEditRequest): Promise<MediaGenResponse> {
    const prompt = typeof req?.prompt === 'string' ? req.prompt.trim() : '';
    const rootDir = this.currentRootDir();
    if (!prompt) return { ok: false, error: 'prompt is required' };
    const mod = await (this.modPromise ??= this.loader());
    if (!mod?.editImage) return { ok: false, error: 'core image edit module unavailable' };
    const env: NodeJS.ProcessEnv = { ...process.env };
    try {
      const imagePath = await this.resolveImageInput(req?.imageAssetId, req?.imagePath);
      if (!imagePath) return { ok: false, error: 'imagePath or imageAssetId is required' };
      const provider = optionalMediaIdentifier(req.provider, 'provider');
      const model = optionalMediaIdentifier(req.model, 'model');
      if (provider) env.CODEBUDDY_IMAGE_PROVIDER = provider;
      if (model) env.CODEBUDDY_IMAGE_MODEL = model;
      const selections = validateEditSelections(req.selections);
      const roots = this.mediaWorkspaceRoots();
      const source = req.imageAssetId
        ? { dataUrl: await imagePathToDataUrl(imagePath), sourcePath: imagePath }
        : await approvedDesignImagePathToDataUrl(imagePath, roots);
      const result = await mod.editImage({
        prompt,
        imageUrl: source.dataUrl,
        sourceRef: source.sourcePath,
        ...(req.maskDataUrl !== undefined ? { maskUrl: validateMaskDataUrl(req.maskDataUrl) } : {}),
        ...(selections.length ? { selections } : {}),
      }, { env, rootDir });
      if (!result.outputPath) return { ok: false, error: 'image editing returned no local path' };
      const output = await approvedDesignImagePathToDataUrl(result.outputPath, roots);
      if (samePath(source.sourcePath, output.sourcePath)) {
        throw new Error('image editing must create a new version without overwriting its source');
      }
      const historyStore = await this.getImageEditHistoryStore(rootDir);
      if (!historyStore) throw new Error('Design View history store is unavailable');
      const history = await historyStore.record(source.sourcePath, output.sourcePath);
      return {
        ok: true,
        outputPath: output.sourcePath,
        url: `file://${output.sourcePath}`,
        history,
      };
    } catch (error) {
      return { ok: false, error: error instanceof Error ? error.message : String(error) };
    }
  }

  async getImageEditHistory(imagePath: string): Promise<ImageEditHistoryResponse> {
    const candidate = typeof imagePath === 'string' ? imagePath.trim() : '';
    if (!candidate) return { ok: false, error: 'imagePath is required' };
    try {
      const roots = this.mediaWorkspaceRoots();
      const canonicalPath = await resolveApprovedDesignImagePath(candidate, roots);
      const historyStore = await this.getImageEditHistoryStore(this.currentRootDir(), { optional: true });
      if (!historyStore) return { ok: true };
      const history = await historyStore.findByPath(canonicalPath);
      if (!history) return { ok: true };

      // The private file is still treated as untrusted at read time: every
      // stored path must independently pass the current realpath boundary.
      const versions: ImageEditHistory['versions'] = [];
      for (const version of history.versions) {
        const validatedPath = await resolveApprovedDesignImagePath(version.path, roots);
        if (!samePath(validatedPath, version.path)) {
          throw new Error('Design View history contains a non-canonical path');
        }
        versions.push({ ...version, path: validatedPath });
      }
      return { ok: true, history: { ...history, versions } };
    } catch (error) {
      return { ok: false, error: error instanceof Error ? error.message : String(error) };
    }
  }

  private mediaWorkspaceRoots(): string[] {
    return [this.currentRootDir(), ...this.mediaWorkspaceRootsLoader()];
  }

  private currentRootDir(): string {
    const root = typeof this.rootDir === 'function' ? this.rootDir() : this.rootDir;
    return root || homedir();
  }

  private async resolveImageInput(assetId?: string, legacyPath?: string): Promise<string> {
    if (assetId) {
      if (!this.assetPathResolver) throw new Error('creative asset registry unavailable');
      return this.assetPathResolver(assetId);
    }
    return typeof legacyPath === 'string' ? legacyPath.trim() : '';
  }

  private async getImageEditHistoryStore(rootDir = this.currentRootDir(), options: { optional?: boolean } = {}): Promise<ImageEditHistoryStore | null> {
    const rootReal = await realpath(rootDir);
    const cached = this.imageEditHistoryStores.get(rootReal);
    if (cached) return cached;
    const codeBuddyDir = join(rootDir, '.codebuddy');
    const mediaDir = join(codeBuddyDir, 'media-generation');
    if (options.optional) {
      try {
        await lstat(mediaDir);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw error;
      }
    }
    await requireRealDirectory(codeBuddyDir);
    await requireRealDirectory(mediaDir);
    const mediaReal = await realpath(mediaDir);
    if (!samePath(mediaReal, join(rootReal, '.codebuddy', 'media-generation'))) {
      throw new Error('Design View history root crosses a symbolic link');
    }
    const store = new ImageEditHistoryStore(mediaReal);
    this.imageEditHistoryStores.set(rootReal, store);
    return store;
  }

  async generateVideo(req: VideoGenRequest): Promise<MediaGenResponse> {
    const prompt = (req?.prompt ?? '').trim();
    if (!prompt) return { ok: false, error: 'prompt is required' };
    const mod = await (this.modPromise ??= this.loader());
    if (!mod?.generateVideo) return { ok: false, error: 'core video generation module unavailable' };
    try {
      const rootDir = this.currentRootDir();
      const imagePath = await this.resolveImageInput(req.imageAssetId, req.imagePath);
      const referencePaths = req.referenceAssetIds?.length
        ? await Promise.all(req.referenceAssetIds.slice(0, 3).map((id) => this.resolveImageInput(id)))
        : (req.referenceImagePaths ?? []).slice(0, 3);
      const imageUrl = imagePath
        ? req.imageAssetId
          ? await imagePathToDataUrl(imagePath)
          : (await approvedDesignImagePathToDataUrl(imagePath, this.mediaWorkspaceRoots())).dataUrl
        : undefined;
      const referenceImageUrls = req.referenceAssetIds?.length
        ? await Promise.all(referencePaths.map(imagePathToDataUrl))
        : await Promise.all(referencePaths.map(async (path) =>
          (await approvedDesignImagePathToDataUrl(path, this.mediaWorkspaceRoots())).dataUrl));
      const result = await mod.generateVideo({
        prompt,
        aspectRatio: req.aspect,
        duration: req.duration,
        audio: req.audio,
        model: req.model,
        resolution: '720p',
        ...(imageUrl ? { imageUrl } : {}),
        ...(referenceImageUrls.length ? { referenceImageUrls } : {}),
      }, { env: process.env, rootDir });
      const outputPath = result.outputPath ?? result.video ?? undefined;
      if (!outputPath) return { ok: false, error: 'video generation returned no local path' };
      return { ok: true, outputPath, url: outputPath.startsWith('http') ? outputPath : `file://${outputPath}` };
    } catch (error) {
      return { ok: false, error: error instanceof Error ? error.message : String(error) };
    }
  }

  async getCapabilities(): Promise<MediaGenCapabilities> {
    const mod = await (this.modPromise ??= this.loader());
    const imageProvider = process.env.CODEBUDDY_IMAGE_PROVIDER ?? 'openai';
    const provider = process.env.CODEBUDDY_VIDEO_PROVIDER ?? (process.env.FAL_KEY ? 'fal' : 'xai');
    const model = process.env.CODEBUDDY_VIDEO_MODEL ?? (provider === 'fal' ? 'pixverse-v6' : 'grok-imagine-video');
    let imageEditing = Boolean(mod?.editImage);
    let imageMasking = Boolean(mod?.editImage) && imageProvider === 'openai';
    if (mod?.getImageEditCapabilities) {
      try {
        const capabilities = await mod.getImageEditCapabilities({ env: process.env, rootDir: this.currentRootDir() });
        imageEditing = capabilities.available;
        imageMasking = capabilities.available && capabilities.alphaMasking;
      } catch {
        imageEditing = false;
        imageMasking = false;
      }
    }
    return {
      imageGeneration: Boolean(mod?.generateImage),
      imageReferences: imageEditing,
      imageEditing,
      imageMasking,
      videoGeneration: Boolean(mod?.generateVideo),
      videoReferences: Boolean(mod?.generateVideo),
      firstFrame: Boolean(mod?.generateVideo),
      lastFrame: false,
      audio: true,
      provider,
      model,
    };
  }

  async assembleVideo(req: AssembleVideoRequest): Promise<MediaGenResponse & { duration?: number; warnings?: string[] }> {
    const clips = (req.clips ?? []).filter((clip) => typeof clip === 'string' && clip.trim()).slice(0, 50);
    if (clips.length < 2) return { ok: false, error: 'at least two video clips are required' };
    if (clips.some((clip) => !/\.(mp4|webm|mov|mkv)$/i.test(clip))) return { ok: false, error: 'film assembly accepts video clips only' };
    const assembler = await (this.assemblerPromise ??= this.assemblerLoader());
    if (!assembler?.assembleFilm) return { ok: false, error: 'film assembler unavailable' };
    try {
      const approvedClips = await Promise.all(clips.map((clip) => resolveApprovedGeneratedVideoPath(clip, this.mediaWorkspaceRoots())));
      const result = await assembler.assembleFilm({
        clips: approvedClips,
        transitions: 'dissolve',
        transitionDuration: 0.5,
        resolution: '1080p',
        aspectRatio: req.aspect ?? '16:9',
        rootDir: this.currentRootDir(),
        name: req.name?.trim() || 'flow-studio-film',
      });
      if (!result.success || !result.outputPath) return { ok: false, error: result.error ?? 'film assembly failed', warnings: result.warnings };
      const outputPath = await resolveApprovedGeneratedFilmOutput(result.outputPath, this.mediaWorkspaceRoots());
      let metadataPath: string | undefined;
      if (req.editorial) {
        const title = req.editorial.title.trim();
        const description = req.editorial.description.trim();
        const duration = result.estimatedDuration ?? 0;
        const assets = this.assetMetadataResolver
          ? await Promise.all([...new Set(req.editorial.assetIds)].map((id) => this.assetMetadataResolver!(id)))
          : [];
        const quality = assessEditorialQuality({
          publication: true,
          title,
          description,
          prompt: req.editorial.prompt,
          aspect: req.aspect ?? '16:9',
          duration,
          syntheticMediaDisclosure: req.editorial.syntheticMediaDisclosure,
          selectedAssets: assets.map((asset) => ({
            kind: asset.companionId ? 'character' : asset.kind,
            contentTier: asset.contentTier,
            qaStatus: asset.qaStatus,
            companionId: asset.companionId,
          })),
          scenes: approvedClips.map((clip) => ({ prompt: clip, status: 'done', mediaType: 'video' })),
          previousPrompts: req.editorial.previousPrompts,
        });
        const readyForHumanReview = quality.ready
          && req.editorial.syntheticMediaDisclosure
          && req.aspect === '9:16'
          && duration >= 6
          && duration <= 15
          && approvedClips.length >= 3
          && title.length >= 8
          && description.length >= 30;
        metadataPath = `${outputPath}.youtube.json`;
        await writeFile(metadataPath, `${JSON.stringify({
          schemaVersion: 1,
          platform: 'youtube',
          visibility: 'private',
          title,
          description,
          ...(req.editorial.series?.trim() ? { series: req.editorial.series.trim() } : {}),
          madeForKids: false,
          containsSyntheticMedia: req.editorial.syntheticMediaDisclosure,
          humanReviewRequired: true,
          reviewStatus: readyForHumanReview ? 'ready-for-human-review' : 'needs-editorial-work',
          qualityScore: quality.score,
          qualityChecks: quality.checks,
          generatedAt: new Date().toISOString(),
        }, null, 2)}\n`, 'utf8');
      }
      return {
        ok: true,
        outputPath,
        url: `file://${outputPath}`,
        ...(metadataPath ? { metadataPath } : {}),
        duration: result.estimatedDuration,
        warnings: result.warnings,
      };
    } catch (error) {
      return { ok: false, error: error instanceof Error ? error.message : String(error) };
    }
  }
}

async function resolveApprovedGeneratedFilmOutput(outputPath: string, workspaceRoots: Iterable<string>): Promise<string> {
  if (!isAbsolute(outputPath) || outputPath.includes('\0')) throw new Error('film output path is invalid');
  for (const root of workspaceRoots) {
    if (!isAbsolute(root)) continue;
    try {
      const rootReal = await realpath(root);
      const films = join(rootReal, '.codebuddy', 'media-generation', 'films');
      await requireRealDirectory(films);
      const canonical = await realpath(outputPath);
      if (!isWithin(films, canonical)) continue;
      await requireNoSymlinkDescendants(films, canonical);
      const info = await lstat(canonical);
      if (!info.isFile() || info.isSymbolicLink()) continue;
      return canonical;
    } catch {
      // Try the next trusted workspace.
    }
  }
  throw new Error('film output is outside generated-media roots');
}

async function resolveApprovedGeneratedVideoPath(videoPath: string, workspaceRoots: Iterable<string>): Promise<string> {
  if (!isAbsolute(videoPath) || videoPath.includes('\0')) throw new Error('video clip path is invalid');
  for (const root of workspaceRoots) {
    if (!isAbsolute(root)) continue;
    try {
      const rootReal = await realpath(root);
      const videos = join(rootReal, '.codebuddy', 'media-generation', 'videos');
      await requireRealDirectory(videos);
      const canonical = await realpath(videoPath);
      if (!isWithin(videos, canonical)) continue;
      await requireNoSymlinkDescendants(videos, canonical);
      return canonical;
    } catch {
      // Continue through trusted roots and fail closed below.
    }
  }
  throw new Error('video clip is outside generated-media roots');
}

const IMAGE_MIME: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.avif': 'image/avif',
};

async function imagePathToDataUrl(imagePath: string): Promise<string> {
  if (!isAbsolute(imagePath) || imagePath.includes('\0')) throw new Error('reference image path is invalid');
  const extension = extname(imagePath).toLowerCase();
  const mime = IMAGE_MIME[extension];
  if (!mime) throw new Error(`unsupported reference image type: ${extension || 'unknown'}`);
  const handle = await open(imagePath, fsConstants.O_RDONLY | (fsConstants.O_NOFOLLOW ?? 0));
  try {
    const metadata = await handle.stat();
    if (!metadata.isFile() || metadata.size <= 0 || metadata.size > 15 * 1024 * 1024) {
      throw new Error('reference image must be a file smaller than 15 MB');
    }
    const content = await handle.readFile();
    if (extension !== '.gif' && extension !== '.avif' && !hasExpectedImageSignature(content, extension)) {
      throw new Error('reference image content does not match its extension');
    }
    return `data:${mime};base64,${content.toString('base64')}`;
  } finally {
    await handle.close();
  }
}

const DESIGN_IMAGE_MIME: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
};

const MAX_REFERENCE_IMAGE_BYTES = 15 * 1024 * 1024;

/**
 * Resolve a Design View source through trusted workspace roots. The renderer
 * only supplies a candidate path; it never chooses the roots. Generated image
 * sources are confined to `<workspace>/.codebuddy/media-generation/images`.
 * Every descendant is lstat'd so a symlink cannot redirect a cloud upload.
 */
async function approvedDesignImagePathToDataUrl(
  imagePath: string,
  workspaceRoots: Iterable<string>,
): Promise<{ dataUrl: string; sourcePath: string }> {
  const approvedPath = await resolveApprovedDesignImagePath(imagePath, workspaceRoots);
  const extension = extname(approvedPath).toLowerCase();
  const mime = DESIGN_IMAGE_MIME[extension]!;
  const flags = fsConstants.O_RDONLY | (fsConstants.O_NOFOLLOW ?? 0);
  const handle = await open(approvedPath, flags);
  try {
    const metadata = await handle.stat();
    if (!metadata.isFile() || metadata.size <= 0 || metadata.size > MAX_REFERENCE_IMAGE_BYTES) {
      throw new Error('Design View source must be an image file smaller than 15 MB');
    }
    const content = await handle.readFile();
    if (!hasExpectedImageSignature(content, extension)) {
      throw new Error('Design View source content does not match its image type');
    }
    return {
      dataUrl: `data:${mime};base64,${content.toString('base64')}`,
      sourcePath: approvedPath,
    };
  } finally {
    await handle.close();
  }
}

async function resolveApprovedDesignImagePath(
  imagePath: string,
  workspaceRoots: Iterable<string>,
): Promise<string> {
  if (!isAbsolute(imagePath) || imagePath.includes('\0')) {
    throw new Error('Design View source must be an absolute generated-media path');
  }

  const requestedPath = resolve(imagePath);
  let approvedPath: string | null = null;
  const roots = [...new Set([...workspaceRoots]
    .filter((root): root is string => typeof root === 'string' && isAbsolute(root) && !root.includes('\0'))
    .map((root) => resolve(root)))];

  for (const workspaceRoot of roots) {
    let workspaceReal: string;
    try {
      workspaceReal = await realpath(workspaceRoot);
    } catch {
      continue;
    }

    const codeBuddyDir = join(workspaceRoot, '.codebuddy');
    const mediaDir = join(codeBuddyDir, 'media-generation');
    const imagesDir = join(mediaDir, 'images');
    try {
      await requireRealDirectory(codeBuddyDir);
      await requireRealDirectory(mediaDir);
      await requireRealDirectory(imagesDir);
      const imagesReal = await realpath(imagesDir);
      const expectedImagesReal = join(workspaceReal, '.codebuddy', 'media-generation', 'images');
      if (!samePath(imagesReal, expectedImagesReal)) continue;

      const requestedReal = await realpath(requestedPath);
      if (!isWithin(imagesReal, requestedReal)) continue;

      // Accept the configured workspace spelling (which itself may be a
      // user-selected symlink) or its canonical spelling, but reject every
      // symlink below the generated-images trust root.
      if (isWithin(imagesDir, requestedPath)) {
        await requireNoSymlinkDescendants(imagesDir, requestedPath);
      } else if (isWithin(imagesReal, requestedPath)) {
        await requireNoSymlinkDescendants(imagesReal, requestedPath);
      } else {
        continue;
      }
      approvedPath = requestedReal;
      break;
    } catch {
      // A missing directory, boundary mismatch, or symlink is not an approved
      // media root. Try the next trusted workspace and otherwise fail closed.
    }
  }

  if (!approvedPath) {
    throw new Error('Design View source is outside the generated-media roots');
  }

  const extension = extname(approvedPath).toLowerCase();
  const mime = DESIGN_IMAGE_MIME[extension];
  if (!mime) throw new Error(`unsupported Design View image type: ${extension || 'unknown'}`);
  return approvedPath;
}

async function requireRealDirectory(directory: string): Promise<void> {
  const metadata = await lstat(directory);
  if (metadata.isSymbolicLink() || !metadata.isDirectory()) {
    throw new Error('generated-media root contains a symbolic link');
  }
}

async function requireNoSymlinkDescendants(root: string, target: string): Promise<void> {
  const child = relative(root, target);
  if (!child || child === '..' || child.startsWith(`..${sep}`) || isAbsolute(child)) {
    throw new Error('generated-media path escapes its root');
  }
  let cursor = root;
  for (const segment of child.split(sep)) {
    cursor = join(cursor, segment);
    const metadata = await lstat(cursor);
    if (metadata.isSymbolicLink()) throw new Error('generated-media path contains a symbolic link');
  }
}

function isWithin(root: string, target: string): boolean {
  const child = relative(root, target);
  return child !== '' && child !== '..' && !child.startsWith(`..${sep}`) && !isAbsolute(child);
}

function samePath(left: string, right: string): boolean {
  const normalizedLeft = resolve(left);
  const normalizedRight = resolve(right);
  return process.platform === 'win32'
    ? normalizedLeft.toLowerCase() === normalizedRight.toLowerCase()
    : normalizedLeft === normalizedRight;
}

function hasExpectedImageSignature(content: Buffer, extension: string): boolean {
  if (extension === '.png') {
    return content.length >= 8 && content.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
  }
  if (extension === '.jpg' || extension === '.jpeg') {
    return content.length >= 3 && content[0] === 0xff && content[1] === 0xd8 && content[2] === 0xff;
  }
  return extension === '.webp'
    && content.length >= 12
    && content.subarray(0, 4).toString('ascii') === 'RIFF'
    && content.subarray(8, 12).toString('ascii') === 'WEBP';
}

function validateEditSelections(value: ImageEditRequest['selections']): NonNullable<ImageEditRequest['selections']> {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.length > 20) throw new Error('selections must contain at most 20 regions');
  return value.map((selection) => {
    if (!selection || typeof selection !== 'object') throw new Error('each selection must be a normalized region');
    const { x, y, width, height } = selection;
    if (![x, y, width, height].every((entry) => typeof entry === 'number' && Number.isFinite(entry))
      || x < 0 || y < 0 || width <= 0 || height <= 0 || x + width > 1 || y + height > 1) {
      throw new Error('each selection must stay within normalized image bounds');
    }
    return { x, y, width, height };
  });
}

function optionalMediaIdentifier(value: unknown, label: string): string | undefined {
  if (value === undefined) return undefined;
  if (typeof value !== 'string' || !/^[A-Za-z0-9._:/-]{1,160}$/.test(value)) {
    throw new Error(`${label} is invalid`);
  }
  return value;
}

function validateMaskDataUrl(value: string): string {
  if (typeof value !== 'string') throw new Error('mask must be a PNG data URL');
  const match = value.match(/^data:image\/png;base64,([A-Za-z0-9+/=]+)$/);
  if (!match) throw new Error('mask must be a PNG data URL');
  const content = Buffer.from(match[1]!, 'base64');
  if (content.length <= 0 || content.length > MAX_REFERENCE_IMAGE_BYTES) throw new Error('mask must be smaller than 15 MB');
  if (!hasExpectedImageSignature(content, '.png')) throw new Error('mask content must be a PNG image');
  return value;
}
