/**
 * Provider Types
 *
 * Re-exports shared type definitions from @phuetz/ai-providers,
 * plus Code Buddy-specific types and compatibility aliases.
 *
 * Where the shared package uses stricter/different types (e.g., 'anthropic'
 * instead of 'claude', JSONSchema instead of Record<string, unknown>),
 * this module preserves the original Code Buddy types for backward compat.
 */

// Re-export types that are identical in both packages
export type {
  ProviderFeature,
  ToolCall,
  StreamChunk,
  ProviderConfig,
  ModelCapabilities,
  ProviderPricing,
  ErrorCategory,
  ConnectionState,
  ToolWrapper,
  ToolResult,
  JSONSchema,
  FinishReason,
  TokenUsage,
} from '@phuetz/ai-providers';

// Re-export types that need backward-compatible shaping
import type {
  ProviderType as SharedProviderType,
  LLMMessage as SharedLLMMessage,
  LLMResponse as SharedLLMResponse,
  CompletionOptions as SharedCompletionOptions,
  ToolDefinition as SharedToolDefinition,
} from '@phuetz/ai-providers';

// ============================================================================
// Code Buddy ProviderType (includes 'claude' alias used throughout codebase)
// ============================================================================

/**
 * Supported AI provider identifiers.
 * Extends the shared ProviderType with 'claude' (Code Buddy's name for Anthropic).
 */
export type ProviderType = SharedProviderType | 'claude';

// ============================================================================
// LLMMessage (keep content as string for backward compat)
// ============================================================================

/**
 * Standardized message format for LLM communication.
 * Code Buddy uses string content; the shared package allows string | null.
 */
export interface LLMMessage {
  /** The role of the message sender. */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** The content of the message. */
  content: string;
  /** The name of the author of this message. */
  name?: string;
  /** The tool call ID this message is responding to (required for role='tool'). */
  tool_call_id?: string;
  /** The tool calls generated by the model. */
  tool_calls?: SharedLLMMessage['tool_calls'];
  /** Base64-encoded image or image URL (for vision-capable models). */
  image?: string;
}

// ============================================================================
// ToolDefinition (keep parameters as Record<string, unknown>)
// ============================================================================

/**
 * Definition of a tool available to the LLM.
 * Parameters is Record<string, unknown> for backward compatibility.
 */
export interface ToolDefinition {
  /** The name of the tool. */
  name: string;
  /** A description of what the tool does. */
  description: string;
  /** JSON Schema defining the expected parameters. */
  parameters: Record<string, unknown>;
}

// ============================================================================
// LLMResponse (use Code Buddy ProviderType)
// ============================================================================

/**
 * Standardized response from an LLM provider.
 */
export interface LLMResponse {
  /** Unique identifier for the completion. */
  id: string;
  /** The textual content of the response (null if only tools are called). */
  content: string | null;
  /** Any tool calls generated by the model. */
  toolCalls: SharedLLMResponse['toolCalls'];
  /** The reason the generation stopped. */
  finishReason: SharedLLMResponse['finishReason'];
  /** Token usage statistics. */
  usage: SharedLLMResponse['usage'];
  /** The specific model version used. */
  model: string;
  /** The provider that generated the response. */
  provider: ProviderType;
}

// ============================================================================
// CompletionOptions (use Code Buddy ToolDefinition)
// ============================================================================

/**
 * Options for a chat completion request.
 */
export interface CompletionOptions {
  /** The conversation history. */
  messages: LLMMessage[];
  /** List of available tools (optional). */
  tools?: ToolDefinition[];
  /** Sampling temperature (override provider default). */
  temperature?: number;
  /** Maximum tokens to generate (override provider default). */
  maxTokens?: number;
  /** Whether to stream the response. */
  stream?: boolean;
  /** System prompt to prepend or insert into messages. */
  systemPrompt?: string;
  /** Force the model to use tools (mode ANY vs AUTO). */
  forceToolUse?: boolean;
  /** Current iteration in the tool calling loop (used to detect first call). */
  toolCallIteration?: number;
}

// ============================================================================
// Code Buddy-specific types (not in shared package)
// ============================================================================

/** Internal interface for Anthropic API response */
export interface AnthropicResponse {
  id: string;
  model: string;
  content: Array<{ type: string; text?: string; id?: string; name?: string; input?: unknown }>;
  stop_reason: string | null;
  usage: { input_tokens: number; output_tokens: number };
}

/** Internal interface for Anthropic stream events */
export interface AnthropicStreamEvent {
  type: string;
  delta?: { type: string; text?: string; partial_json?: string };
}
