/**
 * Local Krea 2 LoRA training plan (1-click / AI-Toolkit / musubi style).
 * Does not download multi-GB trainers; writes config + script the operator can run.
 */

import fs from 'fs/promises';
import path from 'path';
import type { LoraLocalPlan } from './types.js';
import { loadProjectMeta } from './dataset.js';

export async function writeLocalTrainPlan(
  projectDirectory: string,
  options?: { steps?: number; triggerPhrase?: string; resolution?: number },
): Promise<LoraLocalPlan> {
  const meta = await loadProjectMeta(projectDirectory);
  const trigger = (options?.triggerPhrase ?? meta?.triggerPhrase ?? '').trim();
  const steps = options?.steps ?? 1500;
  const resolution = options?.resolution ?? 768;
  const imagesDir = path.join(projectDirectory, 'images');
  const outDir = path.join(projectDirectory, 'output');
  await fs.mkdir(outDir, { recursive: true });

  const config = {
    job: 'extension',
    config: {
      name: meta?.name ?? path.basename(projectDirectory),
      process: [
        {
          type: 'sd_trainer',
          training_folder: outDir,
          device: 'cuda',
          trigger_word: trigger,
          network: { type: 'lora', linear: 32, linear_alpha: 32 },
          save: { dtype: 'bf16', save_every: 250, max_step_saves_to_keep: 4 },
          datasets: [
            {
              folder_path: imagesDir,
              caption_ext: 'txt',
              caption_dropout_rate: 0.05,
              resolution: [resolution],
            },
          ],
          train: {
            batch_size: 1,
            steps,
            gradient_accumulation: 1,
            train_unet: true,
            train_text_encoder: false,
            noise_scheduler: 'flowmatch',
            optimizer: 'adamw8bit',
            lr: 0.0001,
            dtype: 'bf16',
          },
          model: {
            name_or_path: 'krea/Krea-2-Raw',
            quantize: true,
            low_vram: true,
          },
          sample: {
            sampler: 'flowmatch',
            sample_every: 250,
            width: resolution,
            height: resolution,
            prompts: trigger
              ? [`${trigger} portrait, soft light`, `${trigger} looking at camera`]
              : ['portrait, soft light'],
          },
        },
      ],
    },
    meta: {
      purpose: 'Krea 2 character/style LoRA — local plan generated by Code Buddy',
      notes: [
        'Base model id is a starting point; match the weights your AI-Toolkit / musubi build expects.',
        '16GB VRAM: keep low_vram + quantize; 40–50 images; 1000–1500 steps typical for likeness.',
        'Cloud alternative: buddy lora train cloud <project> (FAL_KEY).',
      ],
    },
  };

  const configPath = path.join(projectDirectory, 'ai-toolkit-krea2.json');
  await fs.writeFile(configPath, JSON.stringify(config, null, 2) + '\n', 'utf8');

  const scriptPath = path.join(projectDirectory, 'train-local.sh');
  await fs.writeFile(scriptPath, buildLocalScript(projectDirectory, configPath), {
    encoding: 'utf8',
    mode: 0o755,
  });

  const readmePath = path.join(projectDirectory, 'LOCAL-TRAIN.md');
  await fs.writeFile(readmePath, buildLocalReadme({ projectDirectory, configPath, scriptPath, steps, trigger }), 'utf8');

  return {
    projectDir: projectDirectory,
    configPath,
    readmePath,
    scriptPath,
    steps: [
      `1. Dataset in ${imagesDir}`,
      `2. Review config ${configPath}`,
      `3. Install AI-Toolkit or musubi-tuner (see LOCAL-TRAIN.md / the Krea 2 LoRA video)`,
      `4. Run: bash ${scriptPath}   # or open AI-Toolkit GUI and load the JSON`,
      `5. Install weights: buddy lora install ${path.join(outDir, '*.safetensors')}`,
    ],
  };
}

function buildLocalScript(projectDir: string, configPath: string): string {
  return `#!/usr/bin/env bash
# Local Krea 2 LoRA training helper (Code Buddy)
# Mirrors the "1-click local" flow from Krea 2 LoRA tutorials — does NOT download multi-GB deps itself.
set -euo pipefail
PROJECT="${projectDir}"
CONFIG="${configPath}"
cd "$PROJECT"

if command -v python3 >/dev/null 2>&1; then
  PY=python3
else
  PY=python
fi

echo "== Code Buddy local LoRA plan =="
echo "Project: $PROJECT"
echo "Config:  $CONFIG"
echo
echo "This script looks for a local trainer; it will not auto-download multi-GB models."
echo

if [[ -n "\${AI_TOOLKIT_DIR:-}" && -f "$AI_TOOLKIT_DIR/run.py" ]]; then
  echo "Using AI_TOOLKIT_DIR=$AI_TOOLKIT_DIR"
  exec "$PY" "$AI_TOOLKIT_DIR/run.py" "$CONFIG"
fi

if [[ -d "$HOME/ai-toolkit" && -f "$HOME/ai-toolkit/run.py" ]]; then
  echo "Using ~/ai-toolkit"
  exec "$PY" "$HOME/ai-toolkit/run.py" "$CONFIG"
fi

if [[ -d "$HOME/DEV/ai-toolkit" && -f "$HOME/DEV/ai-toolkit/run.py" ]]; then
  echo "Using ~/DEV/ai-toolkit"
  exec "$PY" "$HOME/DEV/ai-toolkit/run.py" "$CONFIG"
fi

# Pinokio / portable installs sometimes expose a CLI
if command -v ai-toolkit >/dev/null 2>&1; then
  exec ai-toolkit train "$CONFIG"
fi

cat <<EOF
No local AI-Toolkit found.

Options:
  A) Cloud (cheapest path in Code Buddy):
       CODEBUDDY_LORA_TRAIN=true FAL_KEY=… buddy lora train cloud $(basename "$PROJECT") --steps 1000

  B) Install AI-Toolkit (or follow the 1-click installer from the Krea 2 LoRA video), then:
       export AI_TOOLKIT_DIR=/path/to/ai-toolkit
       bash $PROJECT/train-local.sh

  C) musubi-tuner: point it at images/ + config notes in LOCAL-TRAIN.md

Config ready at:
  $CONFIG
EOF
exit 2
`;
}

function buildLocalReadme(args: {
  projectDirectory: string;
  configPath: string;
  scriptPath: string;
  steps: number;
  trigger: string;
}): string {
  return `# Local Krea 2 LoRA training

Aligned with community “1-click local” + cheapest cloud tutorials (Krea 2 LoRA / AI-Toolkit / musubi).

## Recommended settings (character)

| Param | Value |
|-------|--------|
| Images | 40–50 in \`images/\` |
| Steps | ${args.steps} (1000–1500 typical) |
| Resolution | 768 (faster) or 1024 (detail) |
| Trigger | \`${args.trigger || 'your_trigger'}\` |
| Captions | optional \`.txt\` same-stem; else trigger |

## Path A — Cloud (often cheapest / no VRAM)

\`\`\`bash
export FAL_KEY=…
export CODEBUDDY_LORA_TRAIN=true
buddy lora train cloud ${path.basename(args.projectDirectory)} --steps 1000
# ~$0.003/step on fal (min 100 steps billed) → ~$3 for 1000 steps
\`\`\`

## Path B — Local GPU

1. Install [AI-Toolkit](https://github.com/ostris/ai-toolkit) or musubi-tuner (or the 1-click installer from the video).
2. Ensure base **Krea 2 Raw** weights are available as expected by your trainer.
3. Run:

\`\`\`bash
export AI_TOOLKIT_DIR=/path/to/ai-toolkit
bash ${args.scriptPath}
\`\`\`

Config: \`${args.configPath}\`

16GB VRAM: keep low_vram/quantize; layer offload if needed (~64GB RAM).

## After training

\`\`\`bash
buddy lora install ${path.join(args.projectDirectory, 'output', 'your.safetensors')} --name ${path.basename(args.projectDirectory)}
\`\`\`

Then use ComfyUI with Krea 2 + LoRA, or \`CODEBUDDY_IMAGE_PROVIDER=comfyui\`.
`;
}
