import { test, expect, beforeEach, afterEach, vi } from 'vitest';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';
import { GenerateDocumentExecuteTool } from '../../../src/tools/registry/document-generator-tools';

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'cb-test-generate-doc-'));
  vi.stubEnv('HOME', tmpDir);
  vi.stubEnv('CODEBUDDY_HOME', tmpDir);
});

afterEach(async () => {
  vi.unstubAllEnvs();
  await fs.promises.rm(tmpDir, { recursive: true, force: true });
});

test('generate_document tool creates a docx file', async () => {
  const outputPath = path.join(tmpDir, 'test.docx');
  const tool = new GenerateDocumentExecuteTool();
  
  const result = await tool.execute({
    type: 'docx',
    title: 'Test Document',
    content: '# Hello\nThis is a test document generated by vitest.',
    outputPath: outputPath
  });
  
  expect(result.success).toBe(true);
  expect(fs.existsSync(outputPath)).toBe(true);
  const bytes = fs.readFileSync(outputPath);
  expect(bytes.subarray(0, 2).toString('utf8')).toBe('PK');
  expect(bytes.length).toBeGreaterThan(100);
  console.log('[generate_document]', result.output);
});
