/**
 * Stage Code Buddy bundled skills for Cowork packaging.
 *
 * Cowork's production skill loader reads `resources/skills/<skill>/SKILL.md`,
 * while Code Buddy keeps its bundled skills in
 * `../src/skills/bundled/*.skill.md`. This script stages a fresh packaging
 * tree at build time so release artifacts contain only the current Code Buddy
 * skills, without committing a duplicated tree or packaging local `.claude`
 * development files.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..');
const REPO_ROOT = path.join(PROJECT_ROOT, '..');
const SOURCE_DIR = path.join(REPO_ROOT, 'src', 'skills', 'bundled');
const TARGET_ROOT = path.join(PROJECT_ROOT, '.bundle-resources', 'skills');

/**
 * @param {{ sourceDir?: string; targetRoot?: string }} [options]
 * @returns {number} number of staged skills
 */
function stageBundledSkills(options = {}) {
  const sourceDir = options.sourceDir || SOURCE_DIR;
  const targetRoot = options.targetRoot || TARGET_ROOT;
  const markerFile = path.join(targetRoot, '.generated-by-codebuddy-build');

  if (!fs.existsSync(sourceDir)) {
    throw new Error(`Source directory missing: ${sourceDir}`);
  }

  if (fs.existsSync(targetRoot)) {
    fs.rmSync(targetRoot, { recursive: true, force: true });
  }

  fs.mkdirSync(targetRoot, { recursive: true });

  const sourceFiles = fs
    .readdirSync(sourceDir)
    .filter((name) => name.endsWith('.skill.md'))
    .sort();

  if (sourceFiles.length === 0) {
    throw new Error(`No bundled *.skill.md files found in ${sourceDir}`);
  }

  for (const fileName of sourceFiles) {
    const skillName = fileName.replace(/\.skill\.md$/, '');
    const targetDir = path.join(targetRoot, skillName);
    fs.mkdirSync(targetDir, { recursive: true });
    fs.copyFileSync(path.join(sourceDir, fileName), path.join(targetDir, 'SKILL.md'));
  }

  fs.writeFileSync(
    markerFile,
    'Generated by cowork/scripts/prepare-skills.js. Do not edit by hand.\n',
    'utf8'
  );

  return sourceFiles.length;
}

function main() {
  try {
    const count = stageBundledSkills();
    console.log(`[prepare:skills] Staged ${count} bundled skill(s) at .bundle-resources/skills`);
  } catch (error) {
    console.error(`[prepare:skills] ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}

module.exports = { stageBundledSkills };

if (require.main === module) {
  main();
}
