export const publicMarkdownDocs = [
  'CHANGELOG.md',
  'CLAUDE.md',
  'README.md',
  'cowork/ARCHITECTURE.md',
  'cowork/README.md',
  'cowork/README_zh.md',
  'cowork/RUNNER_AUDIT.md',
  'docs/agents.md',
  'docs/channels.md',
  'docs/channel-a2a-bridge.md',
  'docs/code-buddy-hermes-gap-analysis.md',
  'docs/code-buddy-hermes-gap-audit-2026-05-24.md',
  'docs/computer-use-application-profiles.md',
  'docs/commands.md',
  'docs/configuration.md',
  'docs/context-engine.md',
  'docs/cowork-competitor-audit.md',
  'docs/cowork-guide-fr.md',
  'docs/cowork-pilotability-matrix.md',
  'docs/cowork-user-guide.md',
  'docs/development.md',
  'docs/fleet-guide.md',
  'docs/getting-started.md',
  'docs/hermes-agent-next-todo.md',
  'docs/hermes-agent-official-parity-audit-2026-05-30.md',
  'docs/hermes-agent-power-todo.md',
  'docs/hermes-agent-status.md',
  'docs/hermes-agent-strategy.md',
  'docs/hermes-cowork-cli-improvement-plan.md',
  'docs/infrastructure.md',
  'docs/migration.md',
  'docs/providers.md',
  'docs/reasoning.md',
  'docs/reprise/cli-smoke.md',
  'docs/reprise/fleet-minimal.md',
  'docs/screenshots/README.md',
  'docs/security.md',
  'docs/spec-pipeline.md',
  'docs/tools-reference.md',
  'docs/troubleshooting.md',
  'docs/qa/code-buddy-studio/README.md',
  'docs/qa/code-buddy-studio/feature-qa.md',
  'docs/qa/code-buddy-studio/overnight-qa-campaign.md',
] as const;

export const publicPrivacyDocs = [
  ...publicMarkdownDocs,
  'docs/qa/code-buddy-studio/feature-qa-report.json',
  'docs/qa/code-buddy-studio/overnight-test-datasets.json',
] as const;

export const publicScreenshotDirs = [
  'docs/screenshots',
  'docs/qa/code-buddy-studio/screenshots',
] as const;
