import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCatalog, type CatalogFeature } from '../src/catalog/status.js';

type Language = 'fr' | 'en';
type Counts = { total: number; passed: number; failed: number; unavailable: number };
type Row = { feature: CatalogFeature; commands: string[]; scope: string[] };

const START = '<!-- proven-features:start -->';
const END = '<!-- proven-features:end -->';
const REGENERATE = 'npx tsx scripts/generate-proven-features.ts';
const DOMAINS: Record<string, Record<Language, string>> = {
  'agent-tools': { fr: 'Agent et outils', en: 'Agent and tools' },
  cli: { fr: 'Terminal et configuration', en: 'Terminal and configuration' },
  'context-memory': { fr: 'Contexte et mémoire', en: 'Context and memory' },
  cowork: { fr: 'Application de bureau Cowork', en: 'Cowork desktop app' },
  dgm: { fr: 'Apprentissage et expériences', en: 'Learning and experiments' },
  fleet: { fr: 'Coopération entre agents', en: 'Agent cooperation' },
  media: { fr: 'Médias et montage', en: 'Media and editing' },
  providers: { fr: 'Modèles et fournisseurs', en: 'Models and providers' },
  security: { fr: 'Sécurité et isolation', en: 'Security and isolation' },
  sensory: { fr: 'Voix et perception', en: 'Voice and perception' },
  'server-api': { fr: 'Serveur et API', en: 'Server and API' },
};

function text(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/([\\`*_[\]|])/g, '\\$1').replace(/\r?\n/g, ' ');
}

function code(value: string): string {
  const fence = '`'.repeat(Math.max(0, ...[...value.matchAll(/`+/g)].map((match) => match[0].length)) + 1);
  return `${fence} ${value} ${fence}`;
}

function count(rows: Row[]): Counts {
  return {
    total: rows.length,
    passed: rows.filter(({ feature }) => feature.states.testedInSituation === 'vrai').length,
    failed: rows.filter(({ feature }) => feature.states.testedInSituation === 'faux').length,
    unavailable: rows.filter(({ feature }) => feature.states.testedInSituation === 'inconnu').length,
  };
}

function reason(feature: CatalogFeature): string {
  // Deployment is a different axis. Absence of a trace alone is not a reason
  // why the scenario could not be verified in this environment.
  return feature.reasons.filter((item) => ![
    'Aucune preuve d’exécution valide.', 'Version installée non confirmée.',
  ].includes(item)).join(' ');
}

function state(feature: CatalogFeature, language: Language): string {
  const labels = language === 'fr'
    ? { vrai: 'Prouvée', faux: 'Échec', inconnu: 'Non prouvable ici' }
    : { vrai: 'Proven', faux: 'Failed', inconnu: 'Not verifiable here' };
  return labels[feature.states.testedInSituation];
}

function heading(domain: string, language: Language): string {
  return DOMAINS[domain]?.[language] ?? domain;
}

function traceLink(artifact: string): string {
  return path.posix.relative('docs', artifact).split('/').map(encodeURIComponent).join('/');
}

function assertPublic(content: string): void {
  // Loopback URLs and API paths are valid evidence; machine paths are not.
  if (/(?:\/home\/|\/Users\/|\/data\/|\/tmp\/|[a-z]:[\\/]Users[\\/])|\b[\w.+-]+@[\w.-]+\.[a-z]{2,}\b/i.test(content)) {
    throw new Error('Generated content contains a machine path or email; redact the catalogue or trace first.');
  }
}

function renderPage(rows: Row[], digest: string, language: Language): string {
  const fr = language === 'fr';
  const counts = count(rows);
  const dates = rows.flatMap(({ feature }) => feature.latestEvidence ? [feature.latestEvidence.date] : [])
    .sort((a, b) => Date.parse(a) - Date.parse(b));
  const lines = [
    `<!-- Generated by scripts/generate-proven-features.ts; catalogue SHA-256: ${digest} -->`,
    `# Code Buddy : ${fr ? 'fonctionnalités prouvées' : 'proven features'}`, '',
    fr ? '[English version](PROVEN-FEATURES.md) · [README](../README.md)'
      : '[Version française](FONCTIONNALITES-PROUVEES.md) · [README](../README.md)', '',
    fr ? `**${counts.passed}/${counts.total} prouvées en situation · ${counts.failed} échecs · ${counts.unavailable} non prouvables ici, avec raison.**`
      : `**${counts.passed}/${counts.total} proven in real runs · ${counts.failed} failed · ${counts.unavailable} not verifiable here, with reasons.**`, '',
    fr ? 'Chaque fonctionnalité marquée « prouvée » est reliée à une exécution réelle et à son résultat observé. Les échecs restent visibles.'
      : 'Every feature marked “proven” links to a real execution and its observed result. Failures remain visible.', '',
    fr ? 'Cette page couvre les capacités explicitement suivies dans le [catalogue](catalog/README.md), pas toutes les commandes et métadonnées détectées. « Prouvée » vaut pour le scénario décrit ; cela ne certifie ni tous les usages, ni toutes les plateformes, ni le paquet installé.'
      : 'This page covers the capabilities explicitly tracked in the [catalogue](catalog/README.md), rather than every detected command or tool metadata entry. “Proven” applies to the stated scenario; it does not certify every use, platform or installed package.', '',
    fr ? 'Les commandes sont celles enregistrées dans les traces, y compris les appels directs de composants. Les paramètres entre chevrons et les scripts `_qa/` désignent des fixtures temporaires ; ces lignes ne sont pas toutes des recettes autonomes. Les observations, limites et raisons conservent la langue du catalogue ou de la trace.'
      : 'Commands are recorded from the traces, including direct component calls. Angle-bracket parameters and `_qa/` scripts refer to temporary fixtures; these lines are not all standalone recipes. Observations, limits and reasons retain the language of the catalogue or trace.', '',
    fr ? `Dates des exécutions enregistrées (UTC) : ${dates[0]?.slice(0, 10) ?? '—'} → ${dates.at(-1)?.slice(0, 10) ?? '—'}.`
      : `Recorded execution dates (UTC): ${dates[0]?.slice(0, 10) ?? '—'} → ${dates.at(-1)?.slice(0, 10) ?? '—'}.`, '',
    `## ${fr ? 'Échecs observés' : 'Observed failures'}`, '',
  ];
  const failures = rows.filter(({ feature }) => feature.states.testedInSituation === 'faux');
  if (failures.length) {
    lines.push(fr ? '| Fonctionnalité | Résultat observé | Date (UTC) | Preuve |' : '| Feature | Observed result | Date (UTC) | Evidence |',
      '|---|---|---|---|');
    for (const { feature } of failures) {
      const proof = feature.latestEvidence!;
      lines.push(`| ${text(feature.title)} (${code(feature.id)}) | ${text(proof.summary)} | ${proof.date} | [Trace](${traceLink(proof.artifact)}) |`);
    }
  } else lines.push(fr ? 'Aucun échec actuel enregistré.' : 'No current failure recorded.');
  lines.push('', `## ${fr ? 'Par domaine' : 'By domain'}`, '',
    fr ? '| Domaine | Prouvées / suivies | Échecs | Non prouvables ici |' : '| Domain | Proven / tracked | Failed | Not verifiable here |',
    '|---|---|---|---|');
  const domains = [...new Set(rows.map(({ feature }) => feature.domain!))].sort();
  for (const domain of domains) {
    const c = count(rows.filter(({ feature }) => feature.domain === domain));
    lines.push(`| [${text(heading(domain, language))}](#domain-${domain}) | ${c.passed}/${c.total} | ${c.failed} | ${c.unavailable} |`);
  }
  for (const domain of domains) {
    lines.push('', `<a id="domain-${domain}"></a>`, '', `## ${heading(domain, language)}`, '');
    for (const { feature, commands, scope } of rows.filter(({ feature }) => feature.domain === domain)) {
      const proof = feature.latestEvidence;
      lines.push(`### ${text(feature.title)} · ${code(feature.id)}`, '', text(feature.benefit![language]), '',
        `**${state(feature, language)}** · ${fr ? 'Date de l’exécution (UTC)' : 'Execution date (UTC)'} : ${proof?.date ?? '—'}.`);
      if (proof) {
        lines.push(`${fr ? 'Résultat enregistré' : 'Recorded result'} : ${text(proof.summary)}`,
          `${fr ? 'Commande de preuve enregistrée' : 'Recorded evidence command'} : ${commands.map(code).join(' ; ')}`,
          `[${fr ? 'Trace d’exécution' : 'Execution trace'}](${traceLink(proof.artifact)}) · ${fr ? 'révision testée' : 'tested revision'} : ${code(proof.revision)}.`);
      } else {
        lines.push(fr ? 'Commande de preuve : aucune exécution enregistrée.' : 'Evidence command: no recorded execution.');
      }
      if (feature.states.testedInSituation !== 'vrai') lines.push(`${fr ? 'Raison' : 'Reason'} : ${text(reason(feature))}`);
      if (scope.length) lines.push(`${fr ? 'Portée de l’essai' : 'Run scope'} : ${text(scope.join(' '))}`);
      lines.push('');
    }
  }
  lines.push(`## ${fr ? 'Régénérer et contrôler' : 'Regenerate and check'}`, '',
    fr ? 'Les deux pages et le bloc du README sont générés ensemble depuis l’inventaire, le calcul de `buddy catalog status` et les traces versionnées. Aucun total n’est saisi à la main.'
      : 'Both pages and the README block are generated together from the inventory, the `buddy catalog status` calculation and committed traces. No total is entered manually.', '',
    '```bash', REGENERATE, `${REGENERATE} --check`, 'npm test -- tests/docs/proven-features.test.ts', '```', '');
  return `${lines.join('\n').trimEnd()}\n`;
}

export function updateReadme(readme: string, block: string): string {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start < 0 || end < start || readme.indexOf(START, start + 1) !== -1 || readme.indexOf(END, end + 1) !== -1) {
    throw new Error('README: expected exactly one proven-features marker pair.');
  }
  return readme.slice(0, start) + block + readme.slice(end + END.length);
}

/** Use the same evidence validity calculation as the CLI; do not promote lastProof. */
export function generateProvenFeatures(root: string, revision?: string | null): Record<string, string> {
  if (revision === undefined) {
    try {
      revision = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    } catch { revision = null; }
  }
  const catalog = buildCatalog({ root, revision });
  if (catalog.warnings.length) throw new Error(catalog.warnings.join('\n'));
  const inventoryFile = 'docs/catalog/inventory.json';
  const inventory = JSON.parse(readFileSync(path.join(root, inventoryFile), 'utf8')) as { features: Array<{ id: string }> };
  const ids = new Set(inventory.features.map((feature) => feature.id));
  if (ids.size !== inventory.features.length) throw new Error('Duplicate catalogue IDs.');
  const features = catalog.features.filter((feature) => ids.has(feature.id)).sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
  if (features.length !== ids.size || !features.length) throw new Error('Incomplete catalogue.');
  const inputs = new Set([inventoryFile, ...readdirSync(path.join(root, 'docs/preuves'))
    .filter((name) => name.endsWith('.json')).map((name) => `docs/preuves/${name}`)]);
  const rows = features.map((feature): Row => {
    if (!feature.domain || !feature.benefit?.fr || !feature.benefit.en) throw new Error(`Missing domain or benefit: ${feature.id}`);
    if (!/^[a-z0-9-]+$/.test(feature.domain)) throw new Error(`Invalid domain: ${feature.id}`);
    if (feature.states.testedInSituation !== 'vrai' && !reason(feature)) throw new Error(`Missing verification reason: ${feature.id}`);
    const proof = feature.latestEvidence;
    if (!proof) return { feature, commands: [], scope: [] };
    inputs.add(proof.artifact);
    const trace = readFileSync(path.join(root, proof.artifact), 'utf8');
    const commands = [...trace.matchAll(/^(?:Commande(?: serveur| client)?|Command)\s*:\s*(.+)$/gm)].map((match) => match[1]!.trim());
    if (!commands.length) throw new Error(`Missing recorded command: ${feature.id}`);
    const scope = [...trace.matchAll(/^(?:Limite|Portée|Scope)\s*:\s*(.+)$/gm)].map((match) => match[1]!.trim());
    return { feature, commands, scope };
  });
  // Track even editorial changes in the catalogue, without timestamps or HEAD
  // churn. Current source validity is represented by the computed feature states.
  const hash = createHash('sha256');
  for (const file of [...inputs].sort()) hash.update(file).update('\0').update(readFileSync(path.join(root, file))).update('\0');
  hash.update(JSON.stringify(features));
  const digest = hash.digest('hex');
  const c = count(rows);
  const block = [START, '## Ce qui est prouvé', '',
    `[\`PROUVÉES ${c.passed}/${c.total} | ÉCHECS ${c.failed} | NON PROUVABLES ICI ${c.unavailable}\`](docs/FONCTIONNALITES-PROUVEES.md)`,
    `**${c.passed}/${c.total} fonctionnalités prouvées en situation** ; ${c.failed} échecs affichés et ${c.unavailable} non prouvables ici, avec raison.`,
    'Chaque état « prouvée » renvoie à une exécution réelle : commande, date, résultat observé et limite du scénario.',
    '[Consulter les preuves par domaine](docs/FONCTIONNALITES-PROUVEES.md) · [English: proven features](docs/PROVEN-FEATURES.md)',
    END].join('\n');
  const files = {
    'docs/FONCTIONNALITES-PROUVEES.md': renderPage(rows, digest, 'fr'),
    'docs/PROVEN-FEATURES.md': renderPage(rows, digest, 'en'),
    'README.md': updateReadme(readFileSync(path.join(root, 'README.md'), 'utf8'), block),
  };
  // Check only the generated README block, leaving existing content unrelated
  // to this generator under the repository's normal privacy checks.
  for (const content of [files['docs/FONCTIONNALITES-PROUVEES.md'], files['docs/PROVEN-FEATURES.md'], block]) assertPublic(content);
  return files;
}

export function checkGenerated(root: string, files: Record<string, string>): string[] {
  return Object.entries(files).filter(([file, expected]) => {
    try { return readFileSync(path.join(root, file), 'utf8') !== expected; } catch { return true; }
  }).map(([file]) => file);
}

const script = fileURLToPath(import.meta.url);
if (process.argv[1] && path.resolve(process.argv[1]) === script) {
  try {
    const args = process.argv.slice(2);
    if (args.some((arg) => arg !== '--check') || args.length > 1) throw new Error(`Usage: ${REGENERATE} [--check]`);
    const root = path.resolve(path.dirname(script), '..');
    const files = generateProvenFeatures(root);
    if (args.includes('--check')) {
      const stale = checkGenerated(root, files);
      if (stale.length) throw new Error(`Regenerate with ${REGENERATE}: ${stale.join(', ')}`);
      process.stdout.write('Proven feature pages and README are up to date.\n');
    } else {
      for (const [file, content] of Object.entries(files)) writeFileSync(path.join(root, file), content);
      process.stdout.write(`Generated: ${Object.keys(files).join(', ')}\n`);
    }
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
