import type { ComfyLabUseCaseManifest } from './comfy-lab';

/**
 * Data-only capability catalogue. Matching is case-insensitive substring
 * matching against non-empty local model files, workflow paths and the node
 * names returned by ComfyUI's loopback `/object_info` endpoint.
 */
export const COMFY_LAB_MANIFEST: readonly ComfyLabUseCaseManifest[] = [
  {
    id: 'book-visuals',
    priority: 1,
    eyebrow: 'ÉDITION · PRIORITÉ 1',
    title: 'Couvertures & storyboards',
    summary: 'Décliner une direction artistique en couverture, décors et vignettes de plans.',
    deliverable: 'Planche de couverture + storyboard 16:9 cohérent',
    requirements: [
      {
        id: 'image-model',
        label: 'Modèle image local',
        kind: 'model',
        patterns: ['checkpoints/', 'flux1', 'flux2', 'stable-diffusion', 'sd_turbo'],
        required: true,
      },
      {
        id: 'image-nodes',
        label: 'Nœuds de génération image',
        kind: 'node',
        patterns: ['CheckpointLoaderSimple', 'UNETLoader', 'KSampler'],
        required: true,
      },
      {
        id: 'image-template',
        label: 'Workflow image réutilisable',
        kind: 'template',
        patterns: ['flux', 'sd15', 'text to image', 'storyboard'],
        required: true,
      },
    ],
    cost: {
      api: '0 € d’API en local',
      compute: 'Faible à moyen · lots d’images',
      storage: '≈ 1–15 Go par famille de modèles',
    },
    license: 'Vérifier séparément la licence du checkpoint, des LoRA, polices et références.',
    limits: [
      'Le texte intégré aux images doit être finalisé dans l’outil de mise en page.',
      'La cohérence entre planches dépend de références et graines explicitement conservées.',
    ],
    manualSteps: [
      'Choisir un modèle image dont la licence convient à la diffusion du livre.',
      'Créer une bible visuelle : palette, personnages, décors, format et références.',
      'Valider une couverture maître avant de décliner les plans du storyboard.',
    ],
  },
  {
    id: 'wan-animatic',
    priority: 2,
    eyebrow: 'VIDÉO · PRIORITÉ 2',
    title: 'Animatique locale avec Wan',
    summary: 'Transformer les plans validés en clips courts, puis préparer un montage d’animatique.',
    deliverable: 'Clips Wan courts + feuille de montage',
    requirements: [
      {
        id: 'wan-model',
        label: 'Modèle Wan non vide',
        kind: 'model',
        patterns: ['wan2', 'wan_2', '/wan'],
        required: true,
      },
      {
        id: 'wan-nodes',
        label: 'Nœuds Wan vidéo',
        kind: 'node',
        patterns: ['WanVideoModelLoader', 'WanImageToVideo', 'WanVideoSampler'],
        required: true,
      },
      {
        id: 'wan-template',
        label: 'Workflow Wan',
        kind: 'template',
        patterns: ['wan'],
        required: true,
      },
    ],
    cost: {
      api: '0 € d’API en local',
      compute: 'Élevé · plusieurs minutes par clip selon modèle',
      storage: '≈ 8–40 Go modèles + sorties',
    },
    license: 'La licence varie selon la version Wan et les composants associés ; vérifier l’usage commercial.',
    limits: [
      'Commencer par 3–6 secondes et une définition modérée avant tout upscale.',
      'Les mouvements complexes et les mains restent instables sans contrôles supplémentaires.',
    ],
    manualSteps: [
      'Verrouiller le premier cadre à partir du storyboard approuvé.',
      'Produire un clip court par plan avec mouvement de caméra explicite.',
      'Sélectionner les prises avant interpolation, upscale et montage final.',
    ],
  },
  {
    id: 'character-consistency',
    priority: 3,
    eyebrow: 'DIRECTION ARTISTIQUE · PRIORITÉ 3',
    title: 'Cohérence des personnages',
    summary: 'Maintenir visage, silhouette et costume entre couverture, plans et vidéos.',
    deliverable: 'Bible personnage + références réutilisables',
    requirements: [
      {
        id: 'reference-model',
        label: 'Modèle multi-référence/édition',
        kind: 'model',
        patterns: [
          'flux2',
          'flux.2',
          'klein',
          'qwen-image',
          'qwen_image',
          'qwenimage',
          'ip-adapter',
          'ipadapter',
          'instantid',
          'pulid',
        ],
        required: true,
      },
      {
        id: 'reference-nodes',
        label: 'Nœuds de référence',
        kind: 'node',
        patterns: [
          'FluxKontextMultiReference',
          'ReferenceLatent',
          'TextEncodeQwenImageEdit',
          'IPAdapter',
          'InstantID',
          'PuLID',
        ],
        required: true,
      },
      {
        id: 'reference-template',
        label: 'Workflow de cohérence',
        kind: 'template',
        patterns: [
          'image edit (flux.2 klein',
          'flux2',
          'qwen image edit',
          'image edit (qwen',
          'ipadapter',
          'instantid',
          'pulid',
          'character',
        ],
        required: true,
      },
    ],
    cost: {
      api: '0 € d’API en local',
      compute: 'Moyen · passes de référence additionnelles',
      storage: '≈ 1–8 Go selon encodeur/adaptateur',
    },
    license: 'Consentement et droits sur chaque image de référence requis ; le parcours multi-référence FLUX/Qwen n’exige pas de reconnaissance faciale.',
    limits: [
      'Une ressemblance technique ne constitue pas une autorisation d’exploiter l’identité.',
      'Les changements extrêmes d’âge, angle ou éclairage demandent plusieurs références.',
    ],
    manualSteps: [
      'Constituer une fiche approuvée avec plusieurs vues consenties, sans imposer d’analyse biométrique.',
      'Tester FLUX.2 Klein ou Qwen Image Edit multi-référence sur une planche avant toute la séquence.',
      'Conserver les références, poids et paramètres avec chaque personnage.',
    ],
  },
  {
    id: 'ace-music',
    priority: 4,
    eyebrow: 'AUDIO · PRIORITÉ 4',
    title: 'Musique avec ACE-Step',
    summary: 'Préparer une maquette musicale locale pour bande-annonce, ambiance ou générique.',
    deliverable: 'Maquette musicale + fiche de droits',
    requirements: [
      {
        id: 'ace-model',
        label: 'Modèle ACE-Step non vide',
        kind: 'model',
        patterns: ['ace-step', 'ace_step', '/ace'],
        required: true,
      },
      {
        id: 'ace-nodes',
        label: 'Nœuds ACE-Step',
        kind: 'node',
        patterns: ['TextEncodeAceStepAudio', 'EmptyAceStep'],
        required: true,
      },
      {
        id: 'ace-template',
        label: 'Workflow texte-vers-audio',
        kind: 'template',
        patterns: ['ace-step', 'ace step', 'text to audio'],
        required: true,
      },
    ],
    cost: {
      api: '0 € d’API en local',
      compute: 'Moyen à élevé selon durée',
      storage: '≈ 5–20 Go modèles + stems',
    },
    license: 'Vérifier licence du modèle, conditions commerciales et similarité avec des œuvres existantes.',
    limits: [
      'Une génération ne garantit ni originalité juridique ni absence de proximité musicale.',
      'Le mixage, les niveaux et la synchronisation image restent une étape humaine.',
    ],
    manualSteps: [
      'Définir durée, tempo, instrumentation, structure et émotion sans citer un artiste vivant.',
      'Générer plusieurs maquettes courtes et documenter modèle, graine et prompt.',
      'Faire valider les droits et le mix avant publication.',
    ],
  },
  {
    id: 'avatar',
    priority: 5,
    eyebrow: 'PRÉSENTATION · PRIORITÉ 5',
    title: 'Avatar parlant',
    summary: 'Animer un portrait autorisé pour une présentation ou une lecture courte.',
    deliverable: 'Avatar court avec piste voix séparée',
    requirements: [
      {
        id: 'avatar-model',
        label: 'Modèle avatar non vide',
        kind: 'model',
        patterns: ['liveportrait', 'musetalk', 'longcatavatar', 'kling-avatar'],
        required: true,
      },
      {
        id: 'avatar-nodes',
        label: 'Nœuds avatar/portrait',
        kind: 'node',
        patterns: ['LivePortrait', 'MuseTalk', 'LongCatAvatar', 'KlingAvatar'],
        required: true,
      },
      {
        id: 'avatar-template',
        label: 'Workflow avatar',
        kind: 'template',
        patterns: ['avatar', 'liveportrait', 'talking portrait'],
        required: true,
      },
    ],
    cost: {
      api: '0 € si le workflow reste entièrement local',
      compute: 'Moyen à élevé · visage + synchronisation labiale',
      storage: '≈ 5–30 Go selon pipeline',
    },
    license: 'Consentement explicite de la personne et signalement clair d’un avatar synthétique.',
    limits: [
      'Ne jamais présenter l’avatar comme une prise réelle ni contourner le consentement.',
      'Les profils, occultations et longues séquences dégradent la synchronisation.',
    ],
    manualSteps: [
      'Documenter le consentement et le contexte de diffusion.',
      'Utiliser une source nette et une piste voix approuvée.',
      'Ajouter un marquage visible indiquant que la séquence est synthétique.',
    ],
  },
  {
    id: 'three-d',
    priority: 6,
    eyebrow: '3D · PRIORITÉ 6',
    title: 'Objets & décors 3D',
    summary: 'Évaluer la génération d’un mesh à partir d’une image validée pour prévisualisation.',
    deliverable: 'Mesh de prévisualisation à nettoyer',
    requirements: [
      {
        id: 'three-d-model',
        label: 'Modèle image-vers-3D non vide',
        kind: 'model',
        patterns: ['hunyuan3d', 'hunyuan_3d', 'triposr', 'stablefast3d', 'trellis'],
        required: true,
      },
      {
        id: 'three-d-nodes',
        label: 'Nœuds mesh/3D',
        kind: 'node',
        patterns: ['Hunyuan3D', 'TripoSR', 'VoxelToMesh'],
        required: true,
      },
      {
        id: 'three-d-template',
        label: 'Workflow image-vers-3D',
        kind: 'template',
        patterns: ['hunyuan3d', 'image to model', 'triposr', '3d'],
        required: true,
      },
    ],
    cost: {
      api: '0 € d’API en local',
      compute: 'Élevé · reconstruction puis texture',
      storage: '≈ 10–40 Go modèles + géométries',
    },
    license: 'Vérifier droits des images sources, modèle 3D et textures avant exploitation.',
    limits: [
      'Le mesh généré exige généralement retopologie, UV, matériaux et contrôle d’échelle.',
      'Ce parcours vise la prévisualisation, pas un asset de production prêt à livrer.',
    ],
    manualSteps: [
      'Choisir une image de référence lisible et juridiquement exploitable.',
      'Générer une prévisualisation basse définition avant la texture finale.',
      'Contrôler topologie, normales, échelle et licence dans un logiciel 3D.',
    ],
  },
] as const;
