/**
 * Registry of additive Genspark-inspired Cowork slices delivered in batch 2.
 * Data-only by design: no component imports, no mounting side effects.
 *
 * @module renderer/components/genspark-slices
 */

export interface GensparkSlice {
  id: string;
  title: string;
  roadmap: number;
  category: 'agent' | 'deliverable' | 'action' | 'claw' | 'drive' | 'moa' | 'ux' | 'ui';
  mount: 'labs' | 'composer' | 'chat-inline' | 'settings' | 'panel' | 'primitive';
  componentFile: string;
  logicFile?: string;
  testFile?: string;
  needsData: string;
}

export const GENSPARK_SLICES: GensparkSlice[] = [
  {
    id: 'A1',
    title: 'IntentBar',
    roadmap: 1,
    category: 'agent',
    mount: 'composer',
    componentFile: 'components/IntentBar.tsx',
    logicFile: 'utils/intent-classify.ts',
    testFile: '../../tests/intent-classify.test.ts',
    needsData: 'Suggestions de prompts et callback pour envoyer le texte au composer.',
  },
  {
    id: 'A2',
    title: 'MissionBoard',
    roadmap: 3,
    category: 'agent',
    mount: 'panel',
    componentFile: 'components/MissionBoard.tsx',
    logicFile: 'utils/mission-model.ts',
    testFile: '../../tests/mission-model.test.ts',
    needsData: 'Liste de missions actives avec progression, modèle, durée et callbacks ouvrir/pause/reprise.',
  },
  {
    id: 'A3',
    title: 'MissionResumeMenu',
    roadmap: 5,
    category: 'agent',
    mount: 'panel',
    componentFile: 'components/MissionResumeMenu.tsx',
    logicFile: 'utils/checkpoint-model.ts',
    testFile: '../../tests/checkpoint-model.test.ts',
    needsData: 'Checkpoints mission et callbacks resume/branch vers checkpoint ou rewind.',
  },
  {
    id: 'A4',
    title: 'DryRunPreview',
    roadmap: 7,
    category: 'agent',
    mount: 'chat-inline',
    componentFile: 'components/DryRunPreview.tsx',
    logicFile: 'utils/dryrun-estimate.ts',
    testFile: '../../tests/dryrun-estimate.test.ts',
    needsData: 'Plan d’exécution, estimation coût/tokens/temps et callbacks confirmer/annuler.',
  },
  {
    id: 'A5',
    title: 'GuardrailsBadge',
    roadmap: 7,
    category: 'agent',
    mount: 'panel',
    componentFile: 'components/GuardrailsBadge.tsx',
    needsData: 'Mode d’autonomie courant et libellés des garde-fous actifs.',
  },
  {
    id: 'B0',
    title: 'DeckStudioPanel',
    roadmap: 8,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/deliverables/DeckStudioPanel.tsx',
    logicFile: 'components/deliverables/deck-block-model.ts',
    testFile: '../../tests/deck-block-model.test.ts',
    needsData:
      'FONCTIONNEL (promu) : session agent réelle + bloc ```deck → SlideDeckPreview live + export skill pptx.',
  },
  {
    id: 'B1',
    title: 'SlideDeckBuilder',
    roadmap: 8,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/SlideDeckBuilder.tsx',
    logicFile: 'utils/slide-outline.ts',
    testFile: '../../tests/slide-outline.test.ts',
    needsData: 'Plan de slides contrôlé et callbacks modifier/générer vers le skill PPTX.',
  },
  {
    id: 'B2',
    title: 'SheetAnalystView',
    roadmap: 9,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/SheetAnalystView.tsx',
    logicFile: 'utils/sheet-schema.ts',
    testFile: '../../tests/sheet-schema.test.ts',
    needsData: 'Schéma de table, aperçu de lignes et callback de recherche/remplissage.',
  },
  {
    id: 'B3',
    title: 'DocComposer',
    roadmap: 10,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/DocComposer.tsx',
    logicFile: 'utils/doc-outline.ts',
    testFile: '../../tests/doc-outline.test.ts',
    needsData: 'Sections de document contrôlées et callback génération DOCX.',
  },
  {
    id: 'B4',
    title: 'ImagePromptStudio',
    roadmap: 12,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/ImagePromptStudio.tsx',
    logicFile: 'utils/image-preset.ts',
    testFile: '../../tests/image-preset.test.ts',
    needsData: 'Presets image, résultats de génération et callback prompt final.',
  },
  {
    id: 'B5',
    title: 'ShortVideoStoryboard',
    roadmap: 13,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/ShortVideoStoryboard.tsx',
    logicFile: 'utils/storyboard-model.ts',
    testFile: '../../tests/storyboard-model.test.ts',
    needsData: 'Scènes storyboard et callback de rendu vidéo.',
  },
  {
    id: 'B6',
    title: 'PodcastComposer',
    roadmap: 14,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/PodcastComposer.tsx',
    logicFile: 'utils/podcast-script.ts',
    testFile: '../../tests/podcast-script.test.ts',
    needsData: 'Segments narrés et callback synthèse Piper.',
  },
  {
    id: 'B7',
    title: 'ExportShareSheet',
    roadmap: 15,
    category: 'deliverable',
    mount: 'panel',
    componentFile: 'components/ExportShareSheet.tsx',
    logicFile: 'utils/export-format.ts',
    testFile: '../../tests/export-format.test.ts',
    needsData: 'Référence de livrable, formats disponibles et callbacks export/partage.',
  },
  {
    id: 'C1',
    title: 'BrowserAutopilotPanel',
    roadmap: 19,
    category: 'action',
    mount: 'panel',
    componentFile: 'components/BrowserAutopilotPanel.tsx',
    logicFile: 'utils/autopilot-plan.ts',
    testFile: '../../tests/autopilot-plan.test.ts',
    needsData: 'Étapes de navigation et callbacks start/stop vers BrowserOperator.',
  },
  {
    id: 'C2',
    title: 'ComputerUseViewer',
    roadmap: 20,
    category: 'action',
    mount: 'panel',
    componentFile: 'components/ComputerUseViewer.tsx',
    logicFile: 'utils/perception-model.ts',
    testFile: '../../tests/perception-model.test.ts',
    needsData: 'Capture écran optionnelle, arbre de fichiers perçu et callback pick.',
  },
  {
    id: 'C3',
    title: 'CallLogView',
    roadmap: 17,
    category: 'action',
    mount: 'panel',
    componentFile: 'components/CallLogView.tsx',
    logicFile: 'utils/call-model.ts',
    testFile: '../../tests/call-model.test.ts',
    needsData: 'Transcript d’appel, résumé markdown et statistiques calculées.',
  },
  {
    id: 'D1',
    title: 'ChannelMissionAssign',
    roadmap: 22,
    category: 'claw',
    mount: 'panel',
    componentFile: 'components/ChannelMissionAssign.tsx',
    logicFile: 'utils/channel-mission.ts',
    testFile: '../../tests/channel-mission.test.ts',
    needsData: 'Canaux connectés et callback assignation mission.',
  },
  {
    id: 'D2',
    title: 'WorkerDashboard',
    roadmap: 23,
    category: 'claw',
    mount: 'panel',
    componentFile: 'components/WorkerDashboard.tsx',
    logicFile: 'utils/worker-status.ts',
    testFile: '../../tests/worker-status.test.ts',
    needsData: 'Statut worker 24/7, capacité et compteurs de missions.',
  },
  {
    id: 'D3',
    title: 'RemoteApprovalCard',
    roadmap: 25,
    category: 'claw',
    mount: 'chat-inline',
    componentFile: 'components/RemoteApprovalCard.tsx',
    logicFile: 'utils/approval-model.ts',
    testFile: '../../tests/approval-model.test.ts',
    needsData: 'Demande d’approbation distante et callbacks approve/reject.',
  },
  {
    id: 'D4',
    title: 'MobileSupervisionView',
    roadmap: 24,
    category: 'claw',
    mount: 'panel',
    componentFile: 'components/MobileSupervisionView.tsx',
    needsData: 'Missions condensées et callback action mobile valider/stopper.',
  },
  {
    id: 'E1',
    title: 'DriveGrid',
    roadmap: 26,
    category: 'drive',
    mount: 'panel',
    componentFile: 'components/DriveGrid.tsx',
    logicFile: 'utils/drive-index.ts',
    testFile: '../../tests/drive-index.test.ts',
    needsData: 'Index de livrables versionnés, tags et callbacks ouvrir/taguer.',
  },
  {
    id: 'E2',
    title: 'DeliverableVersionTimeline',
    roadmap: 27,
    category: 'drive',
    mount: 'panel',
    componentFile: 'components/DeliverableVersionTimeline.tsx',
    logicFile: 'utils/version-model.ts',
    testFile: '../../tests/version-model.test.ts',
    needsData: 'Versions d’un livrable et callbacks restore/diff.',
  },
  {
    id: 'E3',
    title: 'ShareLinkDialog',
    roadmap: 28,
    category: 'drive',
    mount: 'panel',
    componentFile: 'components/ShareLinkDialog.tsx',
    logicFile: 'utils/share-perms.ts',
    testFile: '../../tests/share-perms.test.ts',
    needsData: 'Item Drive, permissions choisies et callback création de lien.',
  },
  {
    id: 'F1',
    title: 'ModelComparatorView',
    roadmap: 31,
    category: 'moa',
    mount: 'panel',
    componentFile: 'components/ModelComparatorView.tsx',
    logicFile: 'utils/comparator-model.ts',
    testFile: '../../tests/comparator-model.test.ts',
    needsData: 'Réponses modèles scorées et callback de sélection.',
  },
  {
    id: 'F2',
    title: 'DeliberationPanel',
    roadmap: 32,
    category: 'moa',
    mount: 'panel',
    componentFile: 'components/DeliberationPanel.tsx',
    logicFile: 'utils/deliberation-model.ts',
    testFile: '../../tests/deliberation-model.test.ts',
    needsData: 'Verdicts du council, DHI et citation minoritaire optionnelle.',
  },
  {
    id: 'F3',
    title: 'RoutingVizStrip',
    roadmap: 33,
    category: 'moa',
    mount: 'chat-inline',
    componentFile: 'components/RoutingVizStrip.tsx',
    logicFile: 'utils/routing-model.ts',
    testFile: '../../tests/routing-model.test.ts',
    needsData: 'Décision de routage coût/latence/vie privée.',
  },
  {
    id: 'G1',
    title: 'OneScreenOnboarding',
    roadmap: 34,
    category: 'ux',
    mount: 'settings',
    componentFile: 'components/OneScreenOnboarding.tsx',
    logicFile: 'utils/onboarding-steps.ts',
    testFile: '../../tests/onboarding-steps.test.ts',
    needsData: 'Détection locale Ollama/login et callback de choix.',
  },
  {
    id: 'G2',
    title: 'SkillMarketplaceGallery',
    roadmap: 36,
    category: 'ux',
    mount: 'settings',
    componentFile: 'components/SkillMarketplaceGallery.tsx',
    logicFile: 'utils/marketplace-catalog.ts',
    testFile: '../../tests/marketplace-catalog.test.ts',
    needsData: 'Catalogue de skills et callback import.',
  },
  {
    id: 'G3',
    title: 'OutputTemplatePicker',
    roadmap: 41,
    category: 'ux',
    mount: 'composer',
    componentFile: 'components/OutputTemplatePicker.tsx',
    logicFile: 'utils/output-templates.ts',
    testFile: '../../tests/output-templates.test.ts',
    needsData: 'Templates de sortie et callback de sélection.',
  },
  {
    id: 'G4',
    title: 'MissionReplayView',
    roadmap: 40,
    category: 'ux',
    mount: 'panel',
    componentFile: 'components/MissionReplayView.tsx',
    logicFile: 'utils/replay-model.ts',
    testFile: '../../tests/replay-model.test.ts',
    needsData: 'Événements de run et callback de seek.',
  },
  {
    id: 'G5',
    title: 'MissionCompleteToast',
    roadmap: 39,
    category: 'ux',
    mount: 'chat-inline',
    componentFile: 'components/MissionCompleteToast.tsx',
    logicFile: 'utils/toast-model.ts',
    testFile: '../../tests/toast-model.test.ts',
    needsData: 'Résumé de mission et callbacks ouvrir/fermer.',
  },
  {
    id: 'G6',
    title: 'FocusRunnerView',
    roadmap: 38,
    category: 'ux',
    mount: 'panel',
    componentFile: 'components/FocusRunnerView.tsx',
    needsData: 'Mission active, log live et callback quitter.',
  },
  {
    id: 'NV1',
    title: 'Sparkline',
    roadmap: 43,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/Sparkline.tsx',
    logicFile: 'components/viz/util/scale.ts',
    testFile: '../../tests/viz/scale.test.ts',
    needsData: 'Série de valeurs numériques pour tendance compacte.',
  },
  {
    id: 'NV2',
    title: 'BarChart',
    roadmap: 44,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/BarChart.tsx',
    logicFile: 'components/viz/util/bar-model.ts',
    testFile: '../../tests/viz/bar-model.test.ts',
    needsData: 'Paires libellé/valeur pour comparaison horizontale ou verticale.',
  },
  {
    id: 'NV3',
    title: 'Donut',
    roadmap: 45,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/Donut.tsx',
    logicFile: 'components/viz/util/donut-model.ts',
    testFile: '../../tests/viz/donut-model.test.ts',
    needsData: 'Segments libellés avec valeurs et tons optionnels.',
  },
  {
    id: 'NV4',
    title: 'Heatmap',
    roadmap: 46,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/Heatmap.tsx',
    logicFile: 'components/viz/util/heat-model.ts',
    testFile: '../../tests/viz/heat-model.test.ts',
    needsData: 'Lignes, colonnes et matrice de valeurs numériques.',
  },
  {
    id: 'NV5',
    title: 'TimelineChart',
    roadmap: 47,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/TimelineChart.tsx',
    logicFile: 'components/viz/util/timeline-model.ts',
    testFile: '../../tests/viz/timeline-model.test.ts',
    needsData: 'Événements datés avec libellés et tons.',
  },
  {
    id: 'NV6',
    title: 'StackedBar',
    roadmap: 48,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/StackedBar.tsx',
    logicFile: 'components/viz/util/stacked-model.ts',
    testFile: '../../tests/viz/stacked-model.test.ts',
    needsData: 'Parts empilées libellées avec valeurs et tons.',
  },
  {
    id: 'NV7',
    title: 'GaugeMeter',
    roadmap: 49,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/viz/GaugeMeter.tsx',
    logicFile: 'components/viz/util/gauge-model.ts',
    testFile: '../../tests/viz/gauge-model.test.ts',
    needsData: 'Valeur courante, maximum et ton optionnel.',
  },
  {
    id: 'ND1',
    title: 'SlideDeckPreview',
    roadmap: 50,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/deliverables/SlideDeckPreview.tsx',
    logicFile: 'components/deliverables/slide-deck-preview-model.ts',
    testFile: '../../tests/deliverables/slide-deck-preview-model.test.ts',
    needsData: 'Slides titres et puces pour aperçu de deck.',
  },
  {
    id: 'ND2',
    title: 'SheetPreview',
    roadmap: 51,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/deliverables/SheetPreview.tsx',
    logicFile: 'components/deliverables/sheet-preview-model.ts',
    testFile: '../../tests/deliverables/sheet-preview-model.test.ts',
    needsData: 'Colonnes et lignes de tableur.',
  },
  {
    id: 'ND3',
    title: 'DocPreview',
    roadmap: 52,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/deliverables/DocPreview.tsx',
    logicFile: 'components/deliverables/doc-preview-model.ts',
    testFile: '../../tests/deliverables/doc-preview-model.test.ts',
    needsData: 'Blocs document h1/paragraphe/liste.',
  },
  {
    id: 'NA1',
    title: 'AiDrive',
    roadmap: 53,
    category: 'drive',
    mount: 'labs',
    componentFile: 'components/drive/AiDrive.tsx',
    logicFile: 'components/drive/drive-model.ts',
    testFile: '../../tests/drive/drive-model.test.ts',
    needsData: 'Artefacts de démo avec types, dates et tailles.',
  },
  {
    id: 'NA2',
    title: 'MediaGallery',
    roadmap: 54,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/media-gen/MediaGallery.tsx',
    logicFile: 'components/media-gen/media-model.ts',
    testFile: '../../tests/media-gen/media-model.test.ts',
    needsData: 'Médias générés avec statuts mixtes.',
  },
  {
    id: 'NA3',
    title: 'MediaGenComposer',
    roadmap: 55,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/media-gen/MediaGenComposer.tsx',
    logicFile: 'components/media-gen/media-model.ts',
    testFile: '../../tests/media-gen/media-model.test.ts',
    needsData: 'Mode de génération, prompt et callbacks injectés.',
  },
  {
    id: 'NA4',
    title: 'TemplateGallery',
    roadmap: 56,
    category: 'ui',
    mount: 'labs',
    componentFile: 'components/template-gallery/TemplateGallery.tsx',
    logicFile: 'components/template-gallery/template-gallery-model.ts',
    testFile: '../../tests/template-gallery/template-gallery-model.test.ts',
    needsData: 'Props vides : templates par défaut internes.',
  },
  {
    id: 'NM1',
    title: 'AutonomyDashboard',
    roadmap: 57,
    category: 'agent',
    mount: 'labs',
    componentFile: 'components/os-panels/AutonomyDashboard.tsx',
    logicFile: 'components/os-panels/autonomy-dashboard-model.ts',
    testFile: '../../tests/os-panels/autonomy-dashboard-model.test.ts',
    needsData: 'Posture autonomie, agents, coûts et tours.',
  },
  {
    id: 'NM2',
    title: 'KnowledgeGraphView',
    roadmap: 58,
    category: 'agent',
    mount: 'labs',
    componentFile: 'components/os-panels/KnowledgeGraphView.tsx',
    logicFile: 'components/os-panels/knowledge-graph-view-model.ts',
    testFile: '../../tests/os-panels/knowledge-graph-view-model.test.ts',
    needsData: 'Nœuds typés et arêtes du graphe de connaissance.',
  },
  {
    id: 'NG1',
    title: 'OsStatusBar',
    roadmap: 59,
    category: 'agent',
    mount: 'labs',
    componentFile: 'components/os-panels/OsStatusBar.tsx',
    logicFile: 'components/os-panels/os-status-bar-model.ts',
    testFile: '../../tests/os-panels/os-status-bar-model.test.ts',
    needsData: 'Items de statut OS libellé/valeur/ton.',
  },
  {
    id: 'NG2',
    title: 'MissionControlShell',
    roadmap: 60,
    category: 'agent',
    mount: 'labs',
    componentFile: 'components/os-panels/MissionControlShell.tsx',
    logicFile: 'components/os-panels/mission-control-shell-model.ts',
    testFile: '../../tests/os-panels/mission-control-shell-model.test.ts',
    needsData: 'Slots header/left/main/right injectés par props.',
  },
  {
    id: 'H1',
    title: 'UI primitives',
    roadmap: 42,
    category: 'ui',
    mount: 'primitive',
    componentFile: 'components/ui/{StatTile,Pill,SectionCard,EmptyState}.tsx',
    logicFile: 'utils/ui-tone.ts',
    testFile: '../../tests/ui-tone.test.ts',
    needsData: 'Primitives réutilisables alimentées par props et tons sémantiques.',
  },
  {
    id: 'NI1',
    title: 'StudioChatPanel',
    roadmap: 56,
    category: 'ux',
    mount: 'labs',
    componentFile: 'components/studio-iterate/StudioChatPanel.tsx',
    logicFile: 'components/studio-iterate/iterate-model.ts',
    testFile: '../../tests/studio-iterate/iterate-model.test.ts',
    needsData: 'Conversation d’itération (bolt.new) : demander des modifications à l’app générée.',
  },
  {
    id: 'NI2',
    title: 'ChangedFilesStrip',
    roadmap: 57,
    category: 'ux',
    mount: 'labs',
    componentFile: 'components/studio-iterate/ChangedFilesStrip.tsx',
    needsData: 'Fichiers modifiés au dernier tour (ajoutés/modifiés/supprimés).',
  },
  {
    id: 'NI3',
    title: 'PreviewToolbar',
    roadmap: 58,
    category: 'ux',
    mount: 'labs',
    componentFile: 'components/studio-iterate/PreviewToolbar.tsx',
    needsData: 'Barre de test de la preview : lancer/arrêter, tailles d’écran, recharger.',
  },
  {
    id: 'NA5',
    title: 'MediaGenStudio',
    roadmap: 60,
    category: 'deliverable',
    mount: 'labs',
    componentFile: 'components/media-gen/MediaGenPanel.tsx',
    logicFile: 'components/media-gen/media-gen-wiring.ts',
    testFile: '../../tests/media-gen-service.test.ts',
    needsData: 'Studio d’images branché au vrai image_generate (ComfyUI local / cloud).',
  },
];
