export const reprise6Scripts = [
  ['node-sh', 'run.sh', '#!/usr/bin/env node\nout=`id`', 'shell-backtick'],
  ['python-sh', 'run.sh', '#!/usr/bin/env python3\nout=`id`', 'shell-backtick'],
  ['node-bash', 'run.bash', '#!/usr/bin/env node\nout=`id`', 'shell-backtick'],
  ['node-php', 'run.php', '#!/usr/bin/env node\n$out = `id`;', 'php-backtick'],
  ['shell-js', 'run.js', '#!/bin/sh\nout=`id`', 'shell-backtick'],
  ['php-py', 'run.py', '#!/usr/bin/env php\n$out = `id`;', 'php-backtick'],
  ['perl-pl', 'run.pl', '#!/usr/bin/env perl\nmy $out = `id`;', 'shell-backtick'],
  ['perl-perl', 'run.perl', '#!/usr/bin/env perl\nmy $out = `id`;', 'shell-backtick'],
  ['perl-plain', 'run.pl', 'my $out = `id`;', 'shell-backtick'],
  ['absolute-bin', 'run.sh', '/bin/bash ../payload.txt', 'shell-interpreter'],
  ['absolute-option', 'run.sh', '/bin/bash -e ../payload.txt', 'shell-interpreter'],
  ['extensionless-payload', 'run.sh', '/bin/bash payload', 'shell-interpreter'],
  ['absolute-usr', 'run.sh', '/usr/bin/bash ../payload.txt', 'shell-interpreter'],
  ['quoted-absolute', 'run.sh', '"/bin/bash" ../payload.txt', 'shell-interpreter'],
  ['relative-launcher', 'run.sh', './bin/bash ../payload.txt', 'shell-interpreter'],
  ['env-launcher', 'run.sh', '/usr/bin/env bash ../payload.txt', 'shell-interpreter'],
  ['substitution-launcher', 'run.sh', '$(bash ../payload.txt)', 'shell-interpreter'],
  ['wide-launcher', 'run.sh', 'ｂａｓｈ ../payload.txt', 'shell-interpreter'],
  ['wide-absolute', 'run.sh', '/bin/ｂａｓｈ ../payload.txt', 'shell-interpreter'],
  ['template-secret', 'run.js', 'const secret = `REAL_SECRET`;', 'embedded-secret'],
  ['quoted-template-secret', 'run.js', 'const config = { "SC_API_KEY": `REAL_SECRET` };', 'embedded-secret'],
  ['destructive-spawn', 'run.js', 'spawn("rm", ["-rf", "/"]);', 'destructive-process'],
  ['camel-process', 'run.js', 'safeChildProcess.spawn("id");', 'child_process'],
] as const;
