export const reprise7Scripts = [
  ['absolute-double-dash', '/bin/bash -- ../payload.txt'],
  ['usr-double-dash', '/usr/bin/bash -- ../payload.txt'],
  ['quoted-double-dash', '"/bin/bash" -- ../payload.txt'],
  ['bare-double-dash', 'bash -- ../payload.txt'],
  ['extensionless-double-dash', '/bin/bash -- payload'],
  ['absolute-dash', '/bin/bash - ../payload.txt'],
  ['usr-dash', '/usr/bin/bash - ../payload.txt'],
  ['bare-dash', 'bash - ../payload.txt'],
  ['extensionless-dash', '/bin/bash - payload'],
  ['substitution-double-dash', '$(bash -- ../payload.txt)'],
  ['wide-double-dash', 'ｂａｓｈ -- ../payload.txt'],
  ['wide-absolute-dash', '/bin/ｂａｓｈ - ../payload.txt'],
  ['letter-then-terminator', '/bin/bash -e -- ../payload.txt'],
  ['long-then-terminator', '/bin/bash --posix -- ../payload.txt'],
  ['plus-flag', '/bin/bash +e ../payload.txt'],
  ['plus-option', '/bin/bash +o posix ../payload.txt'],
  ['equals-option-attempt', '/bin/bash --rcfile=../payload.txt'],
  ['quoted-option', '/bin/bash "--" ../payload.txt'],
  ['cyrillic-terminator', 'bаsh -- ../payload.txt'],
  ['zero-width-terminator', 'ba\u200bsh -- ../payload.txt'],
] as const;
