export const reprise3Scripts = [
  ['destructured-rm', 'js', "import { rm } from 'fs';\nrm(target, { recursive: true })"],
  ['bare-rm', 'js', 'rm(target, { recursive: true })'],
  ['bare-rm-options', 'js', 'const opts = { recursive: true }; rm(target, opts)'],
  ['bare-rmdir', 'js', 'rmdir(target, { recursive: true })'],
  ['quoted-rm-control', 'js', 'fs.rmSync(p, { "recursive": true })'],
  ['subprocess-bracket-no-import', 'py', "subprocess['check_output'](['id'])"],
  ['shell-backtick-sh', 'sh', 'out=`id`'],
  ['shell-backtick-bash', 'bash', 'out=`id`'],
  ['literal-before-active-backtick', 'sh', "echo '`text`'; out=`id`"],
  ['fake-heredoc-in-string', 'sh', "echo \"Example <<'DOC'\"\n out=`id`"],
  ['unquoted-heredoc-expands', 'sh', 'cat <<DOC\n`id`\nDOC'],
  ['backtick-after-literal-heredoc', 'sh', "cat <<'DOC'\n`text`\nDOC\nout=`id`"],
  ['double-quoted-backtick', 'sh', 'out="`id`"'],
  ['odd-literal-before-single-backtick', 'sh', "echo '`text'; out=`id`"],
  ['odd-literal-before-multiline-backtick', 'sh', "echo '`text'; out=`id\n`"],
  ['multiline-shell-backtick', 'sh', 'out=`id\n`'],
  ['multiline-php-backtick', 'php', '<?php $out = `id\n`;'],
  ['module-before-inert-constant', 'js', "require('child_process')['spawn']('id'); const child_process = 1;"],
] as const;

export const reprise3Mixed = [
  ['operating-system-mixed', 'Works on any operating system (Linux) and then system("id")'],
  ['file-system-mixed', 'Prefer the file system (local disk); system("id")'],
  ['management-system-mixed', 'A database management system (DBMS); system("id")'],
  ['swift-system-mixed', '```swift\n.font(.system(size: 36)); system("id")\n```'],
  ['system-before-prose', 'system("id"); Works on any operating system (Linux).'],
  ['system-before-swift', '```swift\nsystem("id"); .font(.system(size: 36))\n```'],
  ['quoted-native-after-operating-word', 'An operating system("id")'],
  ['unknown-swift-size', '```swift\n.font(.system(size: command()))\n```'],
  ['documentary-multiline-shell', '```sh\nout=`id\n`\n```'],
  ['documentary-multiline-php', '```php\n$out = `id\n`;\n```'],
  ['html-os-system', '<!-- os.system("id") -->'],
  ['html-native-system', '<!-- system("id") -->'],
] as const;
