import { execFile } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import type { ToolResult } from '../types/index.js';
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function safeRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be absolute'); const resolved = path.resolve(root); if (!(await fs.lstat(resolved)).isDirectory()) throw new Error('root is not a directory'); return resolved; }
function tail(text: string): string { return text.length <= 4000 ? text : text.slice(-4000); }
// npm is a `.cmd` shim on Windows: it only resolves/runs through cmd.exe (Node refuses to spawn .cmd files directly). The argv is fixed, so `shell: true` adds no injection surface.
const NPM_SHELL = process.platform === 'win32';
function run(cwd: string, timeoutMs: number): Promise<{ code: number; stdout: string; stderr: string; timedOut: boolean; durationMs: number }> { const started = Date.now(); return new Promise((resolve) => execFile('npm', ['run', 'build'], { cwd, timeout: timeoutMs, maxBuffer: 20 * 1024 * 1024, shell: NPM_SHELL }, (error, stdout, stderr) => resolve({ code: error ? 1 : 0, stdout: String(stdout ?? ''), stderr: String(stderr ?? ''), timedOut: Boolean(error && 'killed' in error && error.killed), durationMs: Date.now() - started }))); }
export class BuildProjectTool { readonly name = 'build_project'; readonly description = 'Run the package.json build script with a bounded timeout and summarize success/failure.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; const root = await safeRoot(String(input.root ?? '')); const pkg = JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8')) as unknown; if (!isRecord(pkg) || !isRecord(pkg.scripts) || typeof pkg.scripts.build !== 'string') return { success: false, error: 'package.json must declare scripts.build' }; const timeoutMs = Math.min(Math.max(Number(input.timeoutMs) || 120_000, 1_000), 600_000); const result = await run(root, timeoutMs); return { success: !result.timedOut && result.code === 0, output: `Build ${result.code === 0 ? 'passed' : 'failed'} in ${result.durationMs}ms${result.timedOut ? ' (timed out)' : ''}`, data: { root, durationMs: result.durationMs, exitCode: result.code, timedOut: result.timedOut, stdoutTail: tail(result.stdout), stderrTail: tail(result.stderr) } }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const BUILD_PROJECT_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'build_project', description: 'Run only the declared npm build script.', parameters: { type: 'object', properties: { root: { type: 'string' }, timeoutMs: { type: 'number' } }, required: ['root'] } } };
