import { resolveToolPath, getToolWorkingDirectory } from '../utils/tool-execution-context.js';
import * as fs from 'fs/promises';
import * as path from 'path';
import { checkSecretFileAccess } from '../security/secret-files.js';
import { gzipSync } from 'zlib';
import type { ToolResult } from '../types/index.js';
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function safeRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be absolute'); const resolved = path.resolve(getToolWorkingDirectory(), root); if (!(await fs.lstat(resolveToolPath(resolved))).isDirectory()) throw new Error('root is not a directory'); return resolved; }
async function walk(dir: string, root: string, out: Array<{ file: string; size: number; gzipSize: number }>): Promise<void> { for (const entry of await fs.readdir(resolveToolPath(dir), { withFileTypes: true })) { const full = path.join(dir, entry.name); if (entry.isDirectory()) await walk(full, root, out); else if (entry.isFile() && !checkSecretFileAccess(full, 'read').secret) { const buf = await fs.readFile(resolveToolPath(full)); out.push({ file: path.relative(root, full), size: buf.length, gzipSize: gzipSync(buf).length }); } } }
export class BundleAnalyzeTool { readonly name = 'bundle_analyze'; readonly description = 'Analyze a dist/build directory sizes and estimated gzip totals.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; const root = await safeRoot(String(input.root ?? '')); const dist = path.resolve(root, String(input.distDir ?? 'dist')); if (dist !== root && !dist.startsWith(root + path.sep)) return { success: false, error: 'distDir escapes root' }; const files: Array<{ file: string; size: number; gzipSize: number }> = []; await walk(dist, dist, files); files.sort((a, b) => b.size - a.size); const totalSize = files.reduce((s, f) => s + f.size, 0); const totalGzipSize = files.reduce((s, f) => s + f.gzipSize, 0); return { success: true, output: `Bundle: ${files.length} file(s), ${totalSize} bytes, ${totalGzipSize} gzip bytes`, data: { root, distDir: dist, totalSize, totalGzipSize, largest: files.slice(0, Number(input.limit) || 10), files } }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const BUNDLE_ANALYZE_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'bundle_analyze', description: 'Read-only size analysis of a dist directory.', parameters: { type: 'object', properties: { root: { type: 'string' }, distDir: { type: 'string' }, limit: { type: 'number' } }, required: ['root'] } } };
