import * as fs from 'fs/promises';
import * as path from 'path';
import type { ToolResult } from '../types/index.js';

type ColumnType = 'number' | 'date' | 'text' | 'empty';
export interface CsvPreviewData { file: string; columns: string[]; rowCount: number; preview: Record<string, string>[]; inferredTypes: Record<string, ColumnType>; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function assertSafeFile(file: string): Promise<string> { if (!path.isAbsolute(file)) throw new Error('file must be an absolute path'); const resolved = path.resolve(file); if (resolved.startsWith('/etc/') || resolved.startsWith('/dev/') || resolved.startsWith('/proc/') || resolved.startsWith('/sys/') || resolved.includes(`${path.sep}.ssh${path.sep}`)) throw new Error(`Refusing unsafe file: ${resolved}`); if (!(await fs.lstat(resolved)).isFile()) throw new Error(`file is not a regular file: ${resolved}`); return resolved; }
function parseCsv(text: string): string[][] { const rows: string[][] = []; let row: string[] = [], cell = '', quoted = false; for (let i = 0; i < text.length; i += 1) { const char = text[i]; const next = text[i + 1]; if (quoted) { if (char === '"' && next === '"') { cell += '"'; i += 1; } else if (char === '"') quoted = false; else cell += char; continue; } if (char === '"') quoted = true; else if (char === ',') { row.push(cell); cell = ''; } else if (char === '\n') { row.push(cell); rows.push(row); row = []; cell = ''; } else if (char !== '\r') cell += char; } if (cell !== '' || row.length > 0) { row.push(cell); rows.push(row); } return rows; }
function infer(values: string[]): ColumnType { const nonEmpty = values.map((v) => v.trim()).filter(Boolean); if (nonEmpty.length === 0) return 'empty'; if (nonEmpty.every((v) => /^-?\d+(\.\d+)?$/.test(v))) return 'number'; if (nonEmpty.every((v) => !Number.isNaN(Date.parse(v)) && /\d{4}-\d{1,2}-\d{1,2}/.test(v))) return 'date'; return 'text'; }
export class CsvPreviewTool { readonly name = 'csv_preview'; readonly description = 'Preview CSV columns, row count, first rows, and simple inferred column types.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; if (typeof input.file !== 'string' || input.file.trim() === '') return { success: false, error: 'file must be a non-empty absolute path' }; const previewRows = input.previewRows === undefined ? 5 : Number(input.previewRows); if (!Number.isInteger(previewRows) || previewRows < 0 || previewRows > 100) return { success: false, error: 'previewRows must be an integer between 0 and 100' }; const file = await assertSafeFile(input.file); const rows = parseCsv(await fs.readFile(file, 'utf8')); const columns = rows[0] ?? []; const body = rows.slice(1); const preview = body.slice(0, previewRows).map((row) => Object.fromEntries(columns.map((column, index) => [column, row[index] ?? '']))); const inferredTypes = Object.fromEntries(columns.map((column, index) => [column, infer(body.map((row) => row[index] ?? ''))])); const data: CsvPreviewData = { file, columns, rowCount: body.length, preview, inferredTypes }; return { success: true, output: `CSV has ${columns.length} columns and ${body.length} rows`, data }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const CSV_PREVIEW_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'csv_preview', description: 'Preview CSV columns, rows, and inferred types.', parameters: { type: 'object', properties: { file: { type: 'string' }, previewRows: { type: 'number' } }, required: ['file'] } } };
