import * as fs from 'fs/promises';
import * as path from 'path';
import type { ToolResult } from '../types/index.js';
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function safeRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be absolute'); const resolved = path.resolve(root); if (!(await fs.lstat(resolved)).isDirectory()) throw new Error('root is not a directory'); return resolved; }
async function safeFile(root: string, file: string): Promise<string> { const resolved = path.resolve(root, file); if (resolved !== root && !resolved.startsWith(root + path.sep)) throw new Error(`file escapes root: ${file}`); if (!(await fs.lstat(resolved)).isFile()) throw new Error(`file is not a regular file: ${file}`); return resolved; }
function lcs(a: string[], b: string[]): number[][] { const table = Array.from({ length: a.length + 1 }, () => Array<number>(b.length + 1).fill(0)); for (let i = a.length - 1; i >= 0; i--) for (let j = b.length - 1; j >= 0; j--) table[i]![j] = a[i] === b[j] ? table[i + 1]![j + 1]! + 1 : Math.max(table[i + 1]![j]!, table[i]![j + 1]!); return table; }
function unified(aName: string, bName: string, a: string[], b: string[]): string { const table = lcs(a, b); const out = [`--- ${aName}`, `+++ ${bName}`]; let i = 0; let j = 0; while (i < a.length || j < b.length) { if (i < a.length && j < b.length && a[i] === b[j]) { out.push(` ${a[i]}`); i++; j++; } else if (j < b.length && (i === a.length || table[i]![j + 1]! >= table[i + 1]![j]!)) { out.push(`+${b[j]}`); j++; } else if (i < a.length) { out.push(`-${a[i]}`); i++; } } return out.join('\n'); }
export class DiffFilesTool { readonly name = 'diff_files'; readonly description = 'Produce a unified diff between two files under a bounded root using a simple LCS algorithm.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; const root = await safeRoot(String(input.root ?? '')); const left = String(input.left ?? ''); const right = String(input.right ?? ''); const leftPath = await safeFile(root, left); const rightPath = await safeFile(root, right); const leftLines = (await fs.readFile(leftPath, 'utf8')).split(/\r?\n/); const rightLines = (await fs.readFile(rightPath, 'utf8')).split(/\r?\n/); const diff = unified(left, right, leftLines, rightLines); return { success: true, output: diff, data: { root, left, right, diff, changed: diff.split('\n').filter((line) => line.startsWith('+') || line.startsWith('-')).length - 2 } }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const DIFF_FILES_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'diff_files', description: 'Unified diff between two files under root.', parameters: { type: 'object', properties: { root: { type: 'string' }, left: { type: 'string' }, right: { type: 'string' } }, required: ['root', 'left', 'right'] } } };
