import { diagnoseLmResizer } from '../context/lm-resizer-diagnostics.js';
import { execFile } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import { promisify } from 'util';
import type { ToolResult } from '../types/index.js';

const execFileAsync = promisify(execFile);
const CONFIG_FILES = ['tsconfig.json', 'vite.config.ts', 'vite.config.js', '.env.example', 'eslint.config.js', 'package.json'];
export interface EnvDoctorData { root: string; nodeVersion: string; nodeModulesPresent: boolean; npmScripts: string[]; tools: Record<string, boolean>; configFiles: string[]; lmResizer?: Awaited<ReturnType<typeof diagnoseLmResizer>>; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function assertRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be an absolute path'); const resolved = path.resolve(root); if ([path.parse(resolved).root, '/etc', '/dev', '/proc', '/sys', '/run'].includes(resolved)) throw new Error(`Refusing unsafe root: ${resolved}`); if (!(await fs.lstat(resolved)).isDirectory()) throw new Error(`root is not a directory: ${resolved}`); return resolved; }
async function exists(filePath: string): Promise<boolean> { try { await fs.access(filePath); return true; } catch { return false; } }
async function hasTool(name: string): Promise<boolean> { try { await execFileAsync(process.platform === 'win32' ? 'where.exe' : 'which', [name], { timeout: 3000 }); return true; } catch { return false; } }
export class EnvDoctorTool { readonly name = 'env_doctor'; readonly description = 'Diagnose local project environment: Node version, node_modules, npm scripts, key tools, and config files.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; if (typeof input.root !== 'string' || input.root.trim() === '') return { success: false, error: 'root must be a non-empty absolute path' }; const root = await assertRoot(input.root); let npmScripts: string[] = []; const packagePath = path.join(root, 'package.json'); if (await exists(packagePath)) { const pkg = JSON.parse(await fs.readFile(packagePath, 'utf8')) as { scripts?: unknown }; if (isRecord(pkg.scripts)) npmScripts = Object.keys(pkg.scripts).filter((key) => typeof (pkg.scripts as Record<string, unknown>)[key] === 'string').sort(); } const configFiles: string[] = []; for (const file of CONFIG_FILES) if (await exists(path.join(root, file))) configFiles.push(file); const data: EnvDoctorData = { root, nodeVersion: process.version, nodeModulesPresent: await exists(path.join(root, 'node_modules')), npmScripts, tools: { git: await hasTool('git'), docker: await hasTool('docker') }, configFiles, lmResizer: await diagnoseLmResizer() }; return { success: true, output: `Node ${process.version}; ${npmScripts.length} npm scripts; node_modules ${data.nodeModulesPresent ? 'present' : 'missing'}\nLM Resizer (host): ${data.lmResizer?.binary}; tool-output=${data.lmResizer?.toolOutputSupported}; enabled=${data.lmResizer?.enabled}. ${data.lmResizer?.warning}\nHost binaries may not be available in the Bash sandbox; use configured MCP integrations or the host observation optimizer.`, data }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const ENV_DOCTOR_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'env_doctor', description: 'Diagnose project environment read-only.', parameters: { type: 'object', properties: { root: { type: 'string' } }, required: ['root'] } } };
