import { resolveToolPath, getToolWorkingDirectory } from '../utils/tool-execution-context.js';
import { execFile } from '../utils/tool-process.js';
import * as fs from 'fs/promises';
import * as path from 'path';
import { promisify } from 'util';
import type { ToolResult } from '../types/index.js';

const execFileAsync = promisify(execFile);
export interface GitSummaryData { root: string; isRepo: boolean; branch?: string; ahead: number; behind: number; staged: number; modified: number; untracked: number; lastCommit?: { hash: string; subject: string }; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function assertRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be an absolute path'); const resolved = path.resolve(getToolWorkingDirectory(), root); if ([path.parse(resolved).root, '/etc', '/dev', '/proc', '/sys', '/run'].includes(resolved)) throw new Error(`Refusing unsafe root: ${resolved}`); if (!(await fs.lstat(resolveToolPath(resolved))).isDirectory()) throw new Error(`root is not a directory: ${resolved}`); return resolved; }
async function git(root: string, args: string[]): Promise<string> { const { stdout } = await execFileAsync('git', ['-C', root, ...args], { timeout: 5000, maxBuffer: 1024 * 1024 }); return stdout.replace(/\s+$/u, ''); }
export class GitSummaryTool { readonly name = 'git_summary'; readonly description = 'Read-only summary of a git repository status, branch, ahead/behind counters, and last commit.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; if (typeof input.root !== 'string' || input.root.trim() === '') return { success: false, error: 'root must be a non-empty absolute path' }; const root = await assertRoot(input.root); try { await git(root, ['rev-parse', '--is-inside-work-tree']); } catch { const data: GitSummaryData = { root, isRepo: false, ahead: 0, behind: 0, staged: 0, modified: 0, untracked: 0 }; return { success: false, error: 'Not a git repository', data }; } const branch = await git(root, ['branch', '--show-current']); let ahead = 0, behind = 0; try { const counts = await git(root, ['rev-list', '--left-right', '--count', '@{upstream}...HEAD']); const [behindText, aheadText] = counts.split(/\s+/); ahead = Number(aheadText ?? 0); behind = Number(behindText ?? 0); } catch { /* no upstream */ } const status = await git(root, ['status', '--porcelain=v1']); let staged = 0, modified = 0, untracked = 0; for (const line of status.split('\n').filter(Boolean)) { if (line.startsWith('??')) { untracked += 1; continue; } if (line[0] !== ' ') staged += 1; if (line[1] !== ' ') modified += 1; } let lastCommit: GitSummaryData['lastCommit']; try { const last = await git(root, ['log', '-1', '--format=%h%x00%s']); const [hash, subject] = last.split('\u0000'); if (hash && subject !== undefined) lastCommit = { hash, subject }; } catch { /* empty repo */ } const data: GitSummaryData = { root, isRepo: true, branch, ahead, behind, staged, modified, untracked, lastCommit }; return { success: true, output: `Git ${branch || '(detached)'}: ${modified} modified, ${staged} staged, ${untracked} untracked`, data }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const GIT_SUMMARY_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'git_summary', description: 'Read-only git repository summary.', parameters: { type: 'object', properties: { root: { type: 'string' } }, required: ['root'] } } };
