import * as fs from 'fs/promises';
import * as path from 'path';
import type { ToolResult } from '../types/index.js';

export interface JsonQueryData { file: string; path: string; value: unknown; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function assertSafeFile(file: string): Promise<string> { if (!path.isAbsolute(file)) throw new Error('file must be an absolute path'); const resolved = path.resolve(file); if (resolved.startsWith('/etc/') || resolved.startsWith('/dev/') || resolved.startsWith('/proc/') || resolved.startsWith('/sys/') || resolved.includes(`${path.sep}.ssh${path.sep}`)) throw new Error(`Refusing unsafe file: ${resolved}`); const stat = await fs.lstat(resolved); if (!stat.isFile()) throw new Error(`file is not a regular file: ${resolved}`); if (path.extname(resolved).toLowerCase() !== '.json') throw new Error('file must have a .json extension'); return resolved; }
function query(value: unknown, dottedPath: string): unknown { if (dottedPath === '') return value; let current: unknown = value; for (const segment of dottedPath.split('.')) { if (segment === '') throw new Error('path contains an empty segment'); if (Array.isArray(current)) { const index = Number(segment); if (!Number.isInteger(index) || index < 0 || index >= current.length) throw new Error(`Array index not found: ${segment}`); current = current[index]; } else if (isRecord(current)) { if (!(segment in current)) throw new Error(`Path segment not found: ${segment}`); current = current[segment]; } else { throw new Error(`Cannot descend into non-object segment: ${segment}`); } } return current; }
export class JsonQueryTool { readonly name = 'json_query'; readonly description = 'Read a JSON file and return a value addressed by a simple dotted path such as a.items.0.name.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; if (typeof input.file !== 'string' || input.file.trim() === '') return { success: false, error: 'file must be a non-empty absolute path' }; if (typeof input.path !== 'string') return { success: false, error: 'path must be a string' }; const file = await assertSafeFile(input.file); const json = JSON.parse(await fs.readFile(file, 'utf8')) as unknown; const value = query(json, input.path); const data: JsonQueryData = { file, path: input.path, value }; return { success: true, output: JSON.stringify(value, null, 2), data }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const JSON_QUERY_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'json_query', description: 'Query a JSON file using a simple dotted path.', parameters: { type: 'object', properties: { file: { type: 'string' }, path: { type: 'string' } }, required: ['file', 'path'] } } };
