import { resolveToolPath, getToolWorkingDirectory } from '../utils/tool-execution-context.js';
import * as fs from 'fs/promises';
import * as path from 'path';
import type { ToolResult } from '../types/index.js';
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function safeRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be absolute'); const resolved = path.resolve(getToolWorkingDirectory(), root); if (!(await fs.lstat(resolveToolPath(resolved))).isDirectory()) throw new Error('root is not a directory'); return resolved; }
const NON_PERMISSIVE = [/\bAGPL\b/i, /\bGPL\b/i, /\bLGPL\b/i, /\bSSPL\b/i, /\bBUSL\b/i, /\bCommons Clause\b/i];
async function packages(nodeModules: string): Promise<Array<{ name: string; version: string; license: string }>> { const out: Array<{ name: string; version: string; license: string }> = []; for (const entry of await fs.readdir(resolveToolPath(nodeModules), { withFileTypes: true })) { if (entry.name.startsWith('.')) continue; const base = path.join(nodeModules, entry.name); if (entry.isDirectory() && entry.name.startsWith('@')) { for (const scoped of await fs.readdir(resolveToolPath(base), { withFileTypes: true })) if (scoped.isDirectory()) await addPackage(path.join(base, scoped.name), out); } else if (entry.isDirectory()) await addPackage(base, out); } return out; }
async function addPackage(dir: string, out: Array<{ name: string; version: string; license: string }>): Promise<void> { try { const pkg = JSON.parse(await fs.readFile(resolveToolPath(path.join(dir, 'package.json')), 'utf8')) as unknown; if (isRecord(pkg) && typeof pkg.name === 'string') out.push({ name: pkg.name, version: typeof pkg.version === 'string' ? pkg.version : '0.0.0', license: typeof pkg.license === 'string' ? pkg.license : 'UNKNOWN' }); } catch { /* ignore */ } }
export class LicenseCheckTool { readonly name = 'license_check'; readonly description = 'Read package licenses from node_modules package.json files and report non-permissive licenses without network access.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; const root = await safeRoot(String(input.root ?? '')); const nodeModules = path.join(root, 'node_modules'); const deps = await packages(nodeModules); const flagged = deps.filter((dep) => NON_PERMISSIVE.some((pattern) => pattern.test(dep.license))); return { success: flagged.length === 0, output: `Licenses: ${deps.length} package(s), ${flagged.length} non-permissive flagged`, data: { root, total: deps.length, flagged, packages: deps } }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const LICENSE_CHECK_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'license_check', description: 'Read-only dependency license check from node_modules.', parameters: { type: 'object', properties: { root: { type: 'string' } }, required: ['root'] } } };
