import * as fs from 'fs/promises';
import * as path from 'path';
import type { ToolResult } from '../types/index.js';
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function safeRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be absolute'); const resolved = path.resolve(root); if (!(await fs.lstat(resolved)).isDirectory()) throw new Error('root is not a directory'); return resolved; }
async function addPackage(dir: string, out: Array<{ name: string; version: string; license: string }>): Promise<void> { try { const pkg = JSON.parse(await fs.readFile(path.join(dir, 'package.json'), 'utf8')) as unknown; if (isRecord(pkg) && typeof pkg.name === 'string') out.push({ name: pkg.name, version: typeof pkg.version === 'string' ? pkg.version : '0.0.0', license: typeof pkg.license === 'string' ? pkg.license : 'UNKNOWN' }); } catch { /* ignore */ } }
async function collect(nodeModules: string): Promise<Array<{ name: string; version: string; license: string }>> { const out: Array<{ name: string; version: string; license: string }> = []; for (const entry of await fs.readdir(nodeModules, { withFileTypes: true })) { if (entry.name.startsWith('.')) continue; const full = path.join(nodeModules, entry.name); if (entry.isDirectory() && entry.name.startsWith('@')) { for (const scoped of await fs.readdir(full, { withFileTypes: true })) if (scoped.isDirectory()) await addPackage(path.join(full, scoped.name), out); } else if (entry.isDirectory()) await addPackage(full, out); } return out.sort((a, b) => a.name.localeCompare(b.name)); }
export class SbomGenerateTool { readonly name = 'sbom_generate'; readonly description = 'Generate a minimal read-only JSON SBOM from installed dependency package metadata.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; const root = await safeRoot(String(input.root ?? '')); const packages = await collect(path.join(root, 'node_modules')); const sbom = { format: 'codebuddy-minimal-sbom', generatedAt: new Date().toISOString(), root, packages }; return { success: true, output: JSON.stringify(sbom, null, 2), data: sbom }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const SBOM_GENERATE_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'sbom_generate', description: 'Generate a minimal JSON SBOM from node_modules package metadata.', parameters: { type: 'object', properties: { root: { type: 'string' } }, required: ['root'] } } };
