import * as fs from 'fs/promises';
import * as path from 'path';
import { checkSecretFileAccess } from '../security/secret-files.js';
import type { ToolResult } from '../types/index.js';

const IGNORE = new Set(['node_modules', '.git', 'dist']);
const DEFAULT_MARKERS = ['TODO', 'FIXME', 'HACK', 'XXX'];
export interface TodoScanItem { file: string; line: number; type: string; text: string; }
export interface TodoScanData { root: string; total: number; byType: Record<string, TodoScanItem[]>; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
async function assertRoot(root: string): Promise<string> { if (!path.isAbsolute(root)) throw new Error('root must be an absolute path'); const resolved = path.resolve(root); if ([path.parse(resolved).root, '/etc', '/dev', '/proc', '/sys', '/run'].includes(resolved)) throw new Error(`Refusing unsafe root: ${resolved}`); if (!(await fs.lstat(resolved)).isDirectory()) throw new Error(`root is not a directory: ${resolved}`); return resolved; }
function markersFrom(input: unknown): string[] { if (input === undefined) return DEFAULT_MARKERS; if (!Array.isArray(input) || input.some((item) => typeof item !== 'string' || item.trim() === '')) throw new Error('markers must be a non-empty string array'); return input.map((item) => item.toUpperCase()); }
function isBinary(buffer: Buffer): boolean { return buffer.subarray(0, 1024).includes(0); }
export class TodoScanTool { readonly name = 'todo_scan'; readonly description = 'Scan a project for TODO/FIXME/HACK/XXX markers and group results by marker type.'; async execute(input: unknown): Promise<ToolResult> { try { if (!isRecord(input)) return { success: false, error: 'Input must be an object' }; if (typeof input.root !== 'string' || input.root.trim() === '') return { success: false, error: 'root must be a non-empty absolute path' }; const root = await assertRoot(input.root); const markers = markersFrom(input.markers); const markerPattern = new RegExp(`\\b(${markers.map((m) => m.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')).join('|')})\\b[:\\s-]*(.*)`, 'i'); const byType: Record<string, TodoScanItem[]> = Object.fromEntries(markers.map((marker) => [marker, []])); const walk = async (dir: string): Promise<void> => { for (const entry of await fs.readdir(dir, { withFileTypes: true })) { if (IGNORE.has(entry.name)) continue; const abs = path.join(dir, entry.name); if (entry.isDirectory()) { await walk(abs); continue; } if (!entry.isFile() || checkSecretFileAccess(abs, 'read').secret) continue; const buf = await fs.readFile(abs); if (isBinary(buf)) continue; const lines = buf.toString('utf8').split(/\r?\n/); lines.forEach((line, index) => { const match = markerPattern.exec(line); if (!match?.[1]) return; const type = match[1].toUpperCase(); byType[type] ??= []; byType[type].push({ file: path.relative(root, abs), line: index + 1, type, text: (match[2] ?? '').trim() }); }); } }; await walk(root); const total = Object.values(byType).reduce((sum, items) => sum + items.length, 0); const data: TodoScanData = { root, total, byType }; return { success: true, output: `Found ${total} todo markers`, data }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) }; } } }
export const TODO_SCAN_TOOL_DEFINITION = { type: 'function' as const, function: { name: 'todo_scan', description: 'Scan a project for TODO/FIXME/HACK/XXX markers.', parameters: { type: 'object', properties: { root: { type: 'string' }, markers: { type: 'array', items: { type: 'string' } } }, required: ['root'] } } };
